import type { ItemData, MonsterData, SpellData } from './types'

/**
 * A small, hand-authored slice of the SRD 5.1 (Creative Commons CC-BY-4.0),
 * baked into the app as the always-available base fallback for the
 * compendium — works with zero configuration, before a DM ever points the
 * app at a private mirror (content/mirrorStorage.ts) or adds homebrew
 * (content/useHomebrewContent.ts). Deliberately small: this is a fallback/
 * demo set, not an attempt to reproduce the whole SRD — a private mirror is
 * the real path to full content per Phase 5's licensing note in ROADMAP.md.
 */

export const SRD_SPELLS: SpellData[] = [
  {
    key: 'srd:fire-bolt',
    source: 'srd',
    name: 'Fire Bolt',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes {@damage 1d10} fire damage. A flammable object hit by this spell ignites if it isn\'t being worn or carried.',
      'This spell\'s damage increases by {@dice 1d10} when you reach 5th level ({@dice 2d10}), 11th level ({@dice 3d10}), and 17th level ({@dice 4d10}).',
    ],
  },
  {
    key: 'srd:magic-missile',
    source: 'srd',
    name: 'Magic Missile',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals {@damage 1d4 + 1} force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
    ],
  },
  {
    key: 'srd:cure-wounds',
    source: 'srd',
    name: 'Cure Wounds',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger'],
    entries: [
      'A creature you touch regains a number of hit points equal to {@dice 1d8} + your spellcasting ability modifier.',
    ],
  },
  {
    key: 'srd:shield',
    source: 'srd',
    name: 'Shield',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 reaction, which you take when you are hit by an attack or targeted by magic missile',
    range: 'Self',
    components: 'V, S',
    duration: '1 round',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
    ],
  },
  {
    key: 'srd:fireball',
    source: 'srd',
    name: 'Fireball',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M (a tiny ball of bat guano and sulfur)',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'A bright streak flashes from you to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a {@save dex}. A target takes {@damage 8d6} fire damage on a failed save, or half as much damage on a successful one.',
      'The fire spreads around corners. It ignites flammable objects in the area that aren\'t being worn or carried.',
    ],
  },
]

export const SRD_MONSTERS: MonsterData[] = [
  {
    key: 'srd:goblin',
    source: 'srd',
    name: 'Goblin',
    size: 'Small',
    type: 'humanoid (goblinoid)',
    alignment: 'Neutral Evil',
    ac: 15,
    acNote: 'leather armor, shield',
    hp: 7,
    hitDice: '2d6',
    speed: '30 ft.',
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    savingThrows: '',
    skills: 'Stealth +6',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'Common, Goblin',
    cr: '1/4',
    traits: [
      {
        name: 'Nimble Escape',
        entries: ['The goblin can take the Disengage or Hide action as a bonus action on each of its turns.'],
      },
    ],
    actions: [
      {
        name: 'Scimitar',
        entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 2} slashing damage.'],
      },
      {
        name: 'Shortbow',
        entries: [
          'Ranged Weapon Attack: {@hit 4} to hit, range 80/320 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:skeleton',
    source: 'srd',
    name: 'Skeleton',
    size: 'Medium',
    type: 'undead',
    alignment: 'Lawful Evil',
    ac: 13,
    acNote: 'armor scraps',
    hp: 13,
    hitDice: '2d8 + 4',
    speed: '30 ft.',
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: 'poison',
    conditionImmunities: 'exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'understands all languages it knew in life but can\'t speak',
    cr: '1/4',
    traits: [],
    actions: [
      {
        name: 'Shortsword',
        entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.'],
      },
      {
        name: 'Shortbow',
        entries: [
          'Ranged Weapon Attack: {@hit 4} to hit, range 80/320 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:wolf',
    source: 'srd',
    name: 'Wolf',
    size: 'Medium',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 13,
    acNote: 'natural armor',
    hp: 11,
    hitDice: '2d8 + 2',
    speed: '40 ft.',
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    savingThrows: '',
    skills: 'Perception +3, Stealth +4',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 13',
    languages: '',
    cr: '1/4',
    traits: [
      { name: 'Keen Hearing and Smell', entries: ['The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.'] },
      {
        name: 'Pack Tactics',
        entries: ['The wolf has advantage on an attack roll against a creature if at least one of the wolf\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.'],
      },
    ],
    actions: [
      {
        name: 'Bite',
        entries: [
          'Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 2d4 + 2} piercing damage. If the target is a creature, it must succeed on a {@save str} or be knocked prone.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:orc',
    source: 'srd',
    name: 'Orc',
    size: 'Medium',
    type: 'humanoid (orc)',
    alignment: 'Chaotic Evil',
    ac: 13,
    acNote: 'hide armor',
    hp: 15,
    hitDice: '2d8 + 6',
    speed: '30 ft.',
    abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    savingThrows: '',
    skills: 'Intimidation +2',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'Common, Orc',
    cr: '1/2',
    traits: [
      { name: 'Aggressive', entries: ['As a bonus action, the orc can move up to its speed toward a hostile creature that it can see.'] },
    ],
    actions: [
      {
        name: 'Greataxe',
        entries: ['Melee Weapon Attack: {@hit 5} to hit, reach 5 ft., one target. Hit: {@damage 1d12 + 3} slashing damage.'],
      },
      {
        name: 'Javelin',
        entries: [
          'Melee or Ranged Weapon Attack: {@hit 5} to hit, reach 5 ft. or range 30/120 ft., one target. Hit: {@damage 1d6 + 3} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:giant-rat',
    source: 'srd',
    name: 'Giant Rat',
    size: 'Small',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 12,
    acNote: '',
    hp: 7,
    hitDice: '2d6',
    speed: '30 ft.',
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: '',
    cr: '1/8',
    traits: [
      {
        name: 'Pack Tactics',
        entries: ['The rat has advantage on an attack roll against a creature if at least one of the rat\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.'],
      },
    ],
    actions: [
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d4 + 2} piercing damage.'] },
    ],
    legendaryActions: [],
  },
]

export const SRD_ITEMS: ItemData[] = [
  {
    key: 'srd:longsword',
    source: 'srd',
    name: 'Longsword',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '3 lb.',
    value: '15 gp',
    entries: ['Versatile (1d10). {@damage 1d8} slashing damage, or {@damage 1d10} if used with two hands.'],
  },
  {
    key: 'srd:dagger',
    source: 'srd',
    name: 'Dagger',
    type: 'Weapon (simple melee)',
    rarity: 'none',
    weight: '1 lb.',
    value: '2 gp',
    entries: ['Finesse, light, thrown (range 20/60). {@damage 1d4} piercing damage.'],
  },
  {
    key: 'srd:leather-armor',
    source: 'srd',
    name: 'Leather Armor',
    type: 'Armor (light)',
    rarity: 'none',
    weight: '10 lb.',
    value: '10 gp',
    entries: ['AC 11 + Dex modifier.'],
  },
  {
    key: 'srd:shield',
    source: 'srd',
    name: 'Shield',
    type: 'Armor (shield)',
    rarity: 'none',
    weight: '6 lb.',
    value: '10 gp',
    entries: ['+2 AC while wielded.'],
  },
  {
    key: 'srd:potion-of-healing',
    source: 'srd',
    name: 'Potion of Healing',
    type: 'Potion',
    rarity: 'common',
    weight: '0.5 lb.',
    value: '50 gp',
    entries: ['You regain {@dice 2d4 + 2} hit points when you drink this potion.'],
  },
]
