import type {
  BackgroundData,
  ClassData,
  FeatureChoiceOption,
  ItemData,
  MonsterData,
  RaceData,
  SpellData,
  SpellEffectData,
  SubclassData,
} from './types'
import { SKILL_LABELS, type SkillId } from '../character/types'

/**
 * A small, hand-authored slice of the SRD 5.1 (Creative Commons CC-BY-4.0),
 * baked into the app as the always-available base fallback for the
 * compendium — works with zero configuration, before a DM ever points the
 * app at a private mirror (content/mirrorStorage.ts) or adds homebrew
 * (content/useHomebrewContent.ts). Deliberately small: this is a fallback/
 * demo set, not an attempt to reproduce the whole SRD — a private mirror is
 * the real path to full content per Phase 5's licensing note in ROADMAP.md.
 */

export const SRD_SPELLS: SpellData[] = [
  {
    key: 'srd:fire-bolt',
    source: 'srd',
    name: 'Fire Bolt',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes {@damage 1d10} fire damage. A flammable object hit by this spell ignites if it isn\'t being worn or carried.',
      'This spell\'s damage increases by {@dice 1d10} when you reach 5th level ({@dice 2d10}), 11th level ({@dice 3d10}), and 17th level ({@dice 4d10}).',
    ],
  },
  {
    key: 'srd:magic-missile',
    source: 'srd',
    name: 'Magic Missile',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals {@damage 1d4 + 1} force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
    ],
  },
  {
    key: 'srd:cure-wounds',
    source: 'srd',
    name: 'Cure Wounds',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger'],
    entries: [
      'A creature you touch regains a number of hit points equal to {@dice 1d8} + your spellcasting ability modifier.',
    ],
  },
  {
    key: 'srd:shield',
    source: 'srd',
    name: 'Shield',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 reaction, which you take when you are hit by an attack or targeted by magic missile',
    range: 'Self',
    components: 'V, S',
    duration: '1 round',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
    ],
  },
  {
    key: 'srd:fireball',
    source: 'srd',
    name: 'Fireball',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M (a tiny ball of bat guano and sulfur)',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'A bright streak flashes from you to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a {@save dex}. A target takes {@damage 8d6} fire damage on a failed save, or half as much damage on a successful one.',
      'The fire spreads around corners. It ignites flammable objects in the area that aren\'t being worn or carried.',
    ],
  },
  {
    key: 'srd:acid-splash',
    source: 'srd',
    name: 'Acid Splash',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a {@save dex} or take {@damage 1d6} acid damage.',
      'This spell\'s damage increases by {@dice 1d6} when you reach 5th level ({@dice 2d6}), 11th level ({@dice 3d6}), and 17th level ({@dice 4d6}).',
    ],
  },
  {
    key: 'srd:guidance',
    source: 'srd',
    name: 'Guidance',
    level: 0,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Concentration, up to 1 minute',
    classes: ['Cleric', 'Druid'],
    entries: [
      'You touch one willing creature. Once before the spell ends, the target can roll {@dice 1d4} and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check.',
    ],
  },
  {
    key: 'srd:light',
    source: 'srd',
    name: 'Light',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, M (a firefly or phosphorescent moss)',
    duration: '1 hour',
    classes: ['Bard', 'Cleric', 'Sorcerer', 'Wizard'],
    entries: [
      'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet.',
    ],
  },
  {
    key: 'srd:mage-hand',
    source: 'srd',
    name: 'Mage Hand',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '1 minute',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it. You can use your action to control the hand, moving, manipulating, or carrying objects of up to 10 pounds.',
    ],
  },
  {
    key: 'srd:minor-illusion',
    source: 'srd',
    name: 'Minor Illusion',
    level: 0,
    school: 'Illusion',
    castingTime: '1 action',
    range: '30 feet',
    components: 'S, M (a bit of fleece)',
    duration: '1 minute',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again.',
    ],
  },
  {
    key: 'srd:prestidigitation',
    source: 'srd',
    name: 'Prestidigitation',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: 'Up to 1 hour',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'This spell is a minor magical trick that novice spellcasters use for practice: create a harmless sensory effect, light or snuff a small flame, clean or soil an object, chill/warm/flavor nonliving material, make a mark or symbol appear, or create a nonmagical trinket.',
    ],
  },
  {
    key: 'srd:sacred-flame',
    source: 'srd',
    name: 'Sacred Flame',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Cleric'],
    entries: [
      'Flame-like radiance descends on a creature that you can see within range. The target must succeed on a {@save dex} or take {@damage 1d8} radiant damage. The target gains no benefit from cover for this saving throw.',
      'The spell\'s damage increases by {@dice 1d8} when you reach 5th level ({@dice 2d8}), 11th level ({@dice 3d8}), and 17th level ({@dice 4d8}).',
    ],
  },
  {
    key: 'srd:vicious-mockery',
    source: 'srd',
    name: 'Vicious Mockery',
    level: 0,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    classes: ['Bard'],
    entries: [
      'You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you, it must succeed on a {@save wis} or take {@damage 1d4} psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.',
      'This spell\'s damage increases by {@dice 1d4} when you reach 5th level ({@dice 2d4}), 11th level ({@dice 3d4}), and 17th level ({@dice 4d4}).',
    ],
  },
  {
    key: 'srd:burning-hands',
    source: 'srd',
    name: 'Burning Hands',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (15-foot cone)',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a {@save dex}. A target takes {@damage 3d6} fire damage on a failed save, or half as much damage on a successful one.',
      'The fire ignites any flammable objects in the area that aren\'t being worn or carried.',
    ],
  },
  {
    key: 'srd:charm-person',
    source: 'srd',
    name: 'Charm Person',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '1 hour',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'You attempt to charm a humanoid you can see within range. It must make a {@save wis}, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance.',
    ],
  },
  {
    key: 'srd:detect-magic',
    source: 'srd',
    name: 'Detect Magic',
    level: 1,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Concentration, up to 10 minutes',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard'],
    entries: [
      'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object that bears magic, and learn its school of magic, if any.',
      'This spell can be cast as a ritual.',
    ],
  },
  {
    key: 'srd:guiding-bolt',
    source: 'srd',
    name: 'Guiding Bolt',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: '1 round',
    classes: ['Cleric'],
    entries: [
      'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes {@damage 4d6} radiant damage, and the next attack roll made against this target before the end of your next turn has advantage.',
    ],
  },
  {
    key: 'srd:healing-word',
    source: 'srd',
    name: 'Healing Word',
    level: 1,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    classes: ['Bard', 'Cleric', 'Druid'],
    entries: [
      'A creature of your choice that you can see within range regains hit points equal to {@dice 1d4} + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    ],
  },
  {
    key: 'srd:mage-armor',
    source: 'srd',
    name: 'Mage Armor',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M (a piece of cured leather)',
    duration: '8 hours',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it until the spell ends. The target\'s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.',
    ],
  },
  {
    key: 'srd:sleep',
    source: 'srd',
    name: 'Sleep',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M (a pinch of fine sand, rose petals, or a cricket)',
    duration: '1 minute',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    entries: [
      'This spell sends creatures into a magical slumber. Roll {@dice 5d8}; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures).',
      'Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, until it takes damage, or until someone uses an action to shake or slap the sleeper awake.',
    ],
  },
  {
    key: 'srd:thunderwave',
    source: 'srd',
    name: 'Thunderwave',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (15-foot cube)',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    entries: [
      'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a {@save con}. On a failed save, a creature takes {@damage 2d8} thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed.',
      'Unsecured objects that are entirely within the area of effect are automatically pushed 10 feet away from you, and the spell emits a thunderous boom audible out to 300 feet.',
    ],
  },
  {
    key: 'srd:hold-person',
    source: 'srd',
    name: 'Hold Person',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M (a small, straight piece of iron)',
    duration: 'Concentration, up to 1 minute',
    classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'You attempt to paralyze a humanoid you can see within range. It must succeed on a {@save wis} or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw, ending the effect on itself on a success.',
    ],
  },
  {
    key: 'srd:invisibility',
    source: 'srd',
    name: 'Invisibility',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M (an eyelash encased in gum arabic)',
    duration: 'Concentration, up to 1 hour',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. The spell ends for a target that attacks or casts a spell.',
    ],
  },
  {
    key: 'srd:misty-step',
    source: 'srd',
    name: 'Misty Step',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    ],
  },
  {
    key: 'srd:scorching-ray',
    source: 'srd',
    name: 'Scorching Ray',
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes {@damage 2d6} fire damage.',
    ],
  },
]

/** Structured mechanical data (shape/size/range/save/damage) for a small,
 * hand-picked set of common SRD 5.1 area-effect spells — see
 * content/types.ts SpellEffectData's doc comment for why this is separate
 * from SRD_SPELLS above. Matched by name (case-insensitive) against a
 * character's own known spells in components/SpellCastPanel.tsx. */
export const SRD_SPELL_EFFECTS: SpellEffectData[] = [
  { name: 'Fireball', areaShape: 'sphere', areaSizeFt: 20, rangeFt: 150, savingThrow: 'dex', savingThrowEffect: 'half', damageDice: '8d6' },
  { name: 'Burning Hands', areaShape: 'cone', areaSizeFt: 15, rangeFt: 0, savingThrow: 'dex', savingThrowEffect: 'half', damageDice: '3d6' },
  { name: 'Thunderwave', areaShape: 'cube', areaSizeFt: 15, rangeFt: 0, savingThrow: 'con', savingThrowEffect: 'half', damageDice: '2d8' },
  { name: 'Shatter', areaShape: 'sphere', areaSizeFt: 10, rangeFt: 60, savingThrow: 'con', savingThrowEffect: 'half', damageDice: '3d8' },
  { name: 'Cone of Cold', areaShape: 'cone', areaSizeFt: 60, rangeFt: 0, savingThrow: 'con', savingThrowEffect: 'half', damageDice: '8d8' },
  { name: 'Lightning Bolt', areaShape: 'line', areaSizeFt: 100, rangeFt: 0, savingThrow: 'dex', savingThrowEffect: 'half', damageDice: '8d6' },
  { name: 'Spirit Guardians', areaShape: 'sphere', areaSizeFt: 15, rangeFt: 0, savingThrow: 'wis', savingThrowEffect: 'half', damageDice: '3d8' },
  { name: 'Sunbeam', areaShape: 'line', areaSizeFt: 60, rangeFt: 0, savingThrow: 'con', savingThrowEffect: 'half', damageDice: '6d8' },
]

export const SRD_MONSTERS: MonsterData[] = [
  {
    key: 'srd:goblin',
    source: 'srd',
    name: 'Goblin',
    size: 'Small',
    type: 'humanoid (goblinoid)',
    alignment: 'Neutral Evil',
    ac: 15,
    acNote: 'leather armor, shield',
    hp: 7,
    hitDice: '2d6',
    speed: '30 ft.',
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    savingThrows: '',
    skills: 'Stealth +6',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'Common, Goblin',
    cr: '1/4',
    traits: [
      {
        name: 'Nimble Escape',
        entries: ['The goblin can take the Disengage or Hide action as a bonus action on each of its turns.'],
      },
    ],
    actions: [
      {
        name: 'Scimitar',
        entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 2} slashing damage.'],
      },
      {
        name: 'Shortbow',
        entries: [
          'Ranged Weapon Attack: {@hit 4} to hit, range 80/320 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:skeleton',
    source: 'srd',
    name: 'Skeleton',
    size: 'Medium',
    type: 'undead',
    alignment: 'Lawful Evil',
    ac: 13,
    acNote: 'armor scraps',
    hp: 13,
    hitDice: '2d8 + 4',
    speed: '30 ft.',
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: 'poison',
    conditionImmunities: 'exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'understands all languages it knew in life but can\'t speak',
    cr: '1/4',
    traits: [],
    actions: [
      {
        name: 'Shortsword',
        entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.'],
      },
      {
        name: 'Shortbow',
        entries: [
          'Ranged Weapon Attack: {@hit 4} to hit, range 80/320 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:wolf',
    source: 'srd',
    name: 'Wolf',
    size: 'Medium',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 13,
    acNote: 'natural armor',
    hp: 11,
    hitDice: '2d8 + 2',
    speed: '40 ft.',
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    savingThrows: '',
    skills: 'Perception +3, Stealth +4',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 13',
    languages: '',
    cr: '1/4',
    traits: [
      { name: 'Keen Hearing and Smell', entries: ['The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.'] },
      {
        name: 'Pack Tactics',
        entries: ['The wolf has advantage on an attack roll against a creature if at least one of the wolf\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.'],
      },
    ],
    actions: [
      {
        name: 'Bite',
        entries: [
          'Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 2d4 + 2} piercing damage. If the target is a creature, it must succeed on a {@save str} or be knocked prone.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:orc',
    source: 'srd',
    name: 'Orc',
    size: 'Medium',
    type: 'humanoid (orc)',
    alignment: 'Chaotic Evil',
    ac: 13,
    acNote: 'hide armor',
    hp: 15,
    hitDice: '2d8 + 6',
    speed: '30 ft.',
    abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    savingThrows: '',
    skills: 'Intimidation +2',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'Common, Orc',
    cr: '1/2',
    traits: [
      { name: 'Aggressive', entries: ['As a bonus action, the orc can move up to its speed toward a hostile creature that it can see.'] },
    ],
    actions: [
      {
        name: 'Greataxe',
        entries: ['Melee Weapon Attack: {@hit 5} to hit, reach 5 ft., one target. Hit: {@damage 1d12 + 3} slashing damage.'],
      },
      {
        name: 'Javelin',
        entries: [
          'Melee or Ranged Weapon Attack: {@hit 5} to hit, reach 5 ft. or range 30/120 ft., one target. Hit: {@damage 1d6 + 3} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:giant-rat',
    source: 'srd',
    name: 'Giant Rat',
    size: 'Small',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 12,
    acNote: '',
    hp: 7,
    hitDice: '2d6',
    speed: '30 ft.',
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: '',
    cr: '1/8',
    traits: [
      {
        name: 'Pack Tactics',
        entries: ['The rat has advantage on an attack roll against a creature if at least one of the rat\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.'],
      },
    ],
    actions: [
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d4 + 2} piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:rat',
    source: 'srd',
    name: 'Rat',
    size: 'Tiny',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 10,
    acNote: '',
    hp: 1,
    hitDice: '1d4 - 1',
    speed: '20 ft.',
    abilities: { str: 2, dex: 11, con: 9, int: 2, wis: 10, cha: 4 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 30 ft., passive Perception 10',
    languages: '',
    cr: '0',
    traits: [],
    actions: [
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 0} to hit, reach 5 ft., one target. Hit: 1 piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:kobold',
    source: 'srd',
    name: 'Kobold',
    size: 'Small',
    type: 'humanoid (kobold)',
    alignment: 'Lawful Evil',
    ac: 12,
    acNote: '',
    hp: 5,
    hitDice: '2d6 - 2',
    speed: '30 ft.',
    abilities: { str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8 },
    savingThrows: '',
    skills: 'Stealth +4',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 8',
    languages: 'Common, Draconic',
    cr: '1/8',
    traits: [
      {
        name: 'Sunlight Sensitivity',
        entries: ['While in sunlight, the kobold has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.'],
      },
      {
        name: 'Pack Tactics',
        entries: ['The kobold has advantage on an attack roll against a creature if at least one of the kobold\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.'],
      },
    ],
    actions: [
      { name: 'Dagger', entries: ['Melee or Ranged Weapon Attack: {@hit 4} to hit, reach 5 ft. or range 20/60 ft., one target. Hit: {@damage 1d4 + 2} piercing damage.'] },
      { name: 'Sling', entries: ['Ranged Weapon Attack: {@hit 4} to hit, range 30/120 ft., one target. Hit: {@damage 1d4 + 2} bludgeoning damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:bandit',
    source: 'srd',
    name: 'Bandit',
    size: 'Medium',
    type: 'humanoid (any race)',
    alignment: 'Any Non-Lawful',
    ac: 12,
    acNote: 'leather armor',
    hp: 11,
    hitDice: '2d8 + 2',
    speed: '30 ft.',
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 10',
    languages: 'any one language (usually Common)',
    cr: '1/8',
    traits: [],
    actions: [
      { name: 'Scimitar', entries: ['Melee Weapon Attack: {@hit 3} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 1} slashing damage.'] },
      { name: 'Light Crossbow', entries: ['Ranged Weapon Attack: {@hit 3} to hit, range 80/320 ft., one target. Hit: {@damage 1d8 + 1} piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:zombie',
    source: 'srd',
    name: 'Zombie',
    size: 'Medium',
    type: 'undead',
    alignment: 'Neutral Evil',
    ac: 8,
    acNote: '',
    hp: 22,
    hitDice: '3d8 + 9',
    speed: '20 ft.',
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    savingThrows: 'Wis +0',
    skills: '',
    damageResistances: '',
    damageImmunities: 'poison',
    conditionImmunities: 'poisoned',
    senses: 'darkvision 60 ft., passive Perception 8',
    languages: 'understands the languages it knew in life but can\'t speak',
    cr: '1/4',
    traits: [
      {
        name: 'Undead Fortitude',
        entries: ['If damage reduces the zombie to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 hit point instead.'],
      },
    ],
    actions: [
      { name: 'Slam', entries: ['Melee Weapon Attack: {@hit 3} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 1} bludgeoning damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:black-bear',
    source: 'srd',
    name: 'Black Bear',
    size: 'Medium',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 11,
    acNote: 'natural armor',
    hp: 19,
    hitDice: '3d8 + 6',
    speed: '40 ft., climb 30 ft.',
    abilities: { str: 15, dex: 10, con: 14, int: 2, wis: 12, cha: 7 },
    savingThrows: '',
    skills: 'Perception +3',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 13',
    languages: '',
    cr: '1/2',
    traits: [{ name: 'Keen Smell', entries: ['The bear has advantage on Wisdom (Perception) checks that rely on smell.'] }],
    actions: [
      { name: 'Multiattack', entries: ['The bear makes two attacks: one with its bite and one with its claws.'] },
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 3} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.'] },
      { name: 'Claws', entries: ['Melee Weapon Attack: {@hit 3} to hit, reach 5 ft., one target. Hit: {@damage 2d4 + 2} slashing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:brown-bear',
    source: 'srd',
    name: 'Brown Bear',
    size: 'Large',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 11,
    acNote: 'natural armor',
    hp: 34,
    hitDice: '4d10 + 12',
    speed: '40 ft., climb 30 ft.',
    abilities: { str: 19, dex: 10, con: 16, int: 2, wis: 13, cha: 7 },
    savingThrows: '',
    skills: 'Perception +3',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 13',
    languages: '',
    cr: '1',
    traits: [{ name: 'Keen Smell', entries: ['The bear has advantage on Wisdom (Perception) checks that rely on smell.'] }],
    actions: [
      { name: 'Multiattack', entries: ['The bear makes two attacks: one with its bite and one with its claws.'] },
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 6} to hit, reach 5 ft., one target. Hit: {@damage 1d8 + 5} piercing damage.'] },
      { name: 'Claws', entries: ['Melee Weapon Attack: {@hit 6} to hit, reach 5 ft., one target. Hit: {@damage 2d6 + 5} slashing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:giant-spider',
    source: 'srd',
    name: 'Giant Spider',
    size: 'Large',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 14,
    acNote: 'natural armor',
    hp: 26,
    hitDice: '4d10 + 4',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4 },
    savingThrows: '',
    skills: 'Stealth +7',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'blindsight 10 ft., darkvision 60 ft., passive Perception 10',
    languages: '',
    cr: '1',
    traits: [
      { name: 'Spider Climb', entries: ['The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.'] },
      { name: 'Web Sense', entries: ['While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.'] },
      { name: 'Web Walker', entries: ['The spider ignores movement restrictions caused by webbing.'] },
    ],
    actions: [
      {
        name: 'Bite',
        entries: [
          'Melee Weapon Attack: {@hit 5} to hit, reach 5 ft., one creature. Hit: {@damage 1d8} piercing damage, and the target must make a {@save con} against a DC of 11, taking {@damage 2d8} poison damage on a failed save, or half as much on a success.',
        ],
      },
      {
        name: 'Web (Recharge 5-6)',
        entries: [
          'Ranged Weapon Attack: {@hit 5} to hit, range 30/60 ft., one creature. Hit: The target is restrained by webbing. As an action, the restrained creature can make a DC 11 Strength check, escaping on a success.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:ghoul',
    source: 'srd',
    name: 'Ghoul',
    size: 'Medium',
    type: 'undead',
    alignment: 'Chaotic Evil',
    ac: 12,
    acNote: '',
    hp: 22,
    hitDice: '5d8',
    speed: '30 ft.',
    abilities: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: 'poison',
    conditionImmunities: 'charmed, exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'Common',
    cr: '1',
    traits: [],
    actions: [
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 2} to hit, reach 5 ft., one creature. Hit: {@damage 2d6 + 2} piercing damage.'] },
      {
        name: 'Claws',
        entries: [
          'Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one creature that isn\'t undead. Hit: {@damage 2d4 + 2} slashing damage. The target must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:ogre',
    source: 'srd',
    name: 'Ogre',
    size: 'Large',
    type: 'giant',
    alignment: 'Chaotic Evil',
    ac: 11,
    acNote: 'hide armor',
    hp: 59,
    hitDice: '7d10 + 21',
    speed: '40 ft.',
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 8',
    languages: 'Common, Giant',
    cr: '2',
    traits: [],
    actions: [
      { name: 'Greatclub', entries: ['Melee Weapon Attack: {@hit 6} to hit, reach 5 ft., one target. Hit: {@damage 2d8 + 4} bludgeoning damage.'] },
      { name: 'Javelin', entries: ['Melee or Ranged Weapon Attack: {@hit 6} to hit, reach 5 ft. or range 30/120 ft., one target. Hit: {@damage 2d6 + 4} piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:owlbear',
    source: 'srd',
    name: 'Owlbear',
    size: 'Large',
    type: 'monstrosity',
    alignment: 'Unaligned',
    ac: 13,
    acNote: 'natural armor',
    hp: 59,
    hitDice: '7d10 + 21',
    speed: '40 ft.',
    abilities: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    savingThrows: '',
    skills: 'Perception +3',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 13',
    languages: '',
    cr: '3',
    traits: [{ name: 'Keen Sight and Smell', entries: ['The owlbear has advantage on Wisdom (Perception) checks that rely on sight or smell.'] }],
    actions: [
      { name: 'Multiattack', entries: ['The owlbear makes two attacks: one with its beak and one with its claws.'] },
      { name: 'Beak', entries: ['Melee Weapon Attack: {@hit 7} to hit, reach 5 ft., one creature. Hit: {@damage 1d10 + 5} piercing damage.'] },
      { name: 'Claws', entries: ['Melee Weapon Attack: {@hit 7} to hit, reach 5 ft., one target. Hit: {@damage 2d8 + 5} slashing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:wight',
    source: 'srd',
    name: 'Wight',
    size: 'Medium',
    type: 'undead',
    alignment: 'Neutral Evil',
    ac: 14,
    acNote: 'studded leather armor',
    hp: 45,
    hitDice: '6d8 + 18',
    speed: '30 ft.',
    abilities: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    savingThrows: '',
    skills: 'Perception +3, Stealth +4',
    damageResistances: 'necrotic; bludgeoning, piercing, and slashing from nonmagical attacks',
    damageImmunities: 'poison',
    conditionImmunities: 'exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 13',
    languages: 'the languages it knew in life',
    cr: '3',
    traits: [
      {
        name: 'Sunlight Sensitivity',
        entries: ['While in sunlight, the wight has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.'],
      },
    ],
    actions: [
      { name: 'Multiattack', entries: ['The wight makes two longsword attacks or two longbow attacks. It can use its Life Drain in place of one longsword attack.'] },
      {
        name: 'Life Drain',
        entries: [
          'Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one creature. Hit: {@damage 1d6 + 2} necrotic damage. The target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken, and the wight regains hit points equal to that amount. The reduction lasts until the target finishes a long rest. The target dies if this effect reduces its hit point maximum to 0. A humanoid slain by this attack rises 24 hours later as a zombie under the wight\'s control, unless the humanoid is restored to life or its body is destroyed.',
        ],
      },
      { name: 'Longsword', entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d8 + 2} slashing damage, or {@damage 1d10 + 2} if used with two hands.'] },
      { name: 'Longbow', entries: ['Ranged Weapon Attack: {@hit 4} to hit, range 150/600 ft., one target. Hit: {@damage 1d8 + 2} piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:troll',
    source: 'srd',
    name: 'Troll',
    size: 'Large',
    type: 'giant',
    alignment: 'Chaotic Evil',
    ac: 15,
    acNote: 'natural armor',
    hp: 84,
    hitDice: '8d10 + 40',
    speed: '30 ft.',
    abilities: { str: 18, dex: 13, con: 20, int: 7, wis: 9, cha: 7 },
    savingThrows: '',
    skills: 'Perception +2',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 12',
    languages: 'Giant',
    cr: '5',
    traits: [
      { name: 'Keen Smell', entries: ['The troll has advantage on Wisdom (Perception) checks that rely on smell.'] },
      {
        name: 'Regeneration',
        entries: [
          'The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, this trait doesn\'t function at the start of the troll\'s next turn. The troll dies only if it starts its turn with 0 hit points and doesn\'t regenerate.',
        ],
      },
    ],
    actions: [
      { name: 'Multiattack', entries: ['The troll makes three attacks: one with its bite and two with its claws.'] },
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 7} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 4} piercing damage.'] },
      { name: 'Claw', entries: ['Melee Weapon Attack: {@hit 7} to hit, reach 5 ft., one target. Hit: {@damage 2d6 + 4} slashing damage.'] },
    ],
    legendaryActions: [],
  },
]

export const SRD_ITEMS: ItemData[] = [
  {
    key: 'srd:longsword',
    source: 'srd',
    name: 'Longsword',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '3 lb.',
    value: '15 gp',
    entries: ['Versatile (1d10). {@damage 1d8} slashing damage, or {@damage 1d10} if used with two hands.'],
  },
  {
    key: 'srd:dagger',
    source: 'srd',
    name: 'Dagger',
    type: 'Weapon (simple melee)',
    rarity: 'none',
    weight: '1 lb.',
    value: '2 gp',
    entries: ['Finesse, light, thrown (range 20/60). {@damage 1d4} piercing damage.'],
  },
  {
    key: 'srd:leather-armor',
    source: 'srd',
    name: 'Leather Armor',
    type: 'Armor (light)',
    rarity: 'none',
    weight: '10 lb.',
    value: '10 gp',
    entries: ['AC 11 + Dex modifier.'],
  },
  {
    key: 'srd:shield',
    source: 'srd',
    name: 'Shield',
    type: 'Armor (shield)',
    rarity: 'none',
    weight: '6 lb.',
    value: '10 gp',
    entries: ['+2 AC while wielded.'],
  },
  {
    key: 'srd:potion-of-healing',
    source: 'srd',
    name: 'Potion of Healing',
    type: 'Potion',
    rarity: 'common',
    weight: '0.5 lb.',
    value: '50 gp',
    entries: ['You regain {@dice 2d4 + 2} hit points when you drink this potion.'],
  },
  {
    key: 'srd:shortsword',
    source: 'srd',
    name: 'Shortsword',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '2 lb.',
    value: '10 gp',
    entries: ['Finesse, light. {@damage 1d6} piercing damage.'],
  },
  {
    key: 'srd:greatsword',
    source: 'srd',
    name: 'Greatsword',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '6 lb.',
    value: '50 gp',
    entries: ['Heavy, two-handed. {@damage 2d6} slashing damage.'],
  },
  {
    key: 'srd:rapier',
    source: 'srd',
    name: 'Rapier',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '2 lb.',
    value: '25 gp',
    entries: ['Finesse. {@damage 1d8} piercing damage.'],
  },
  {
    key: 'srd:shortbow',
    source: 'srd',
    name: 'Shortbow',
    type: 'Weapon (simple ranged)',
    rarity: 'none',
    weight: '2 lb.',
    value: '25 gp',
    entries: ['Ammunition (range 80/320), two-handed. {@damage 1d6} piercing damage.'],
  },
  {
    key: 'srd:handaxe',
    source: 'srd',
    name: 'Handaxe',
    type: 'Weapon (simple melee)',
    rarity: 'none',
    weight: '2 lb.',
    value: '5 gp',
    entries: ['Light, thrown (range 20/60). {@damage 1d6} slashing damage.'],
  },
  {
    key: 'srd:studded-leather-armor',
    source: 'srd',
    name: 'Studded Leather Armor',
    type: 'Armor (light)',
    rarity: 'none',
    weight: '13 lb.',
    value: '45 gp',
    entries: ['AC 12 + Dex modifier.'],
  },
  {
    key: 'srd:chain-mail',
    source: 'srd',
    name: 'Chain Mail',
    type: 'Armor (heavy)',
    rarity: 'none',
    weight: '55 lb.',
    value: '75 gp',
    entries: ['AC 16. Str 13 required; disadvantage on Stealth checks.'],
  },
  {
    key: 'srd:rope-hempen',
    source: 'srd',
    name: 'Rope, Hempen (50 feet)',
    type: 'Adventuring Gear',
    rarity: 'none',
    weight: '10 lb.',
    value: '1 gp',
    entries: ['Rope has 2 hit points and can be burst with a DC 17 Strength check.'],
  },
  {
    key: 'srd:backpack',
    source: 'srd',
    name: 'Backpack',
    type: 'Adventuring Gear',
    rarity: 'none',
    weight: '5 lb.',
    value: '2 gp',
    entries: ['A backpack can hold one cubic foot or 30 pounds of gear. You can also strap items, such as a bedroll or a coil of rope, to the outside of a backpack.'],
  },
  {
    key: 'srd:torch',
    source: 'srd',
    name: 'Torch',
    type: 'Adventuring Gear',
    rarity: 'none',
    weight: '1 lb.',
    value: '1 cp',
    entries: ['A torch burns for 1 hour, providing bright light in a 20-foot radius and dim light for an additional 20 feet. If you make a melee attack with a burning torch and hit, it deals 1 fire damage.'],
  },
  {
    key: 'srd:thieves-tools',
    source: 'srd',
    name: "Thieves' Tools",
    type: 'Tool',
    rarity: 'none',
    weight: '1 lb.',
    value: '25 gp',
    entries: ['This set includes a small file, lock picks, small mirror on a metal handle, narrow-bladed scissors, and pliers. Proficiency with these tools lets you add your proficiency bonus to checks made to disarm traps or open locks.'],
  },
  {
    key: 'srd:bag-of-holding',
    source: 'srd',
    name: 'Bag of Holding',
    type: 'Wondrous item',
    rarity: 'uncommon',
    weight: '15 lb.',
    value: '',
    entries: [
      'This bag has an interior space considerably larger than its outside dimensions, roughly 2 feet in diameter at the mouth and 4 feet deep. The bag can hold up to 500 pounds, not exceeding a volume of 64 cubic feet. The bag weighs 15 pounds, regardless of its contents.',
      'Placing an object that is small enough to fit inside the bag causes the bag to absorb it, making the object weightless and taking up a negligible amount of space in the bag.',
      'If the bag is overloaded, or if a sharp object pierces it, the bag ruptures and is destroyed, and its contents are scattered in the Astral Plane.',
    ],
  },
]

/** Dragonborn's Draconic Ancestry — determines breath weapon damage type/
 * shape/save and matching damage resistance (SRD 5.1, publicly known 5e
 * rules facts, written in my own words). */
const DRACONIC_ANCESTRY_OPTIONS: FeatureChoiceOption[] = [
  { key: 'black', name: 'Black', description: 'Acid damage, 5×30 ft. line (Dex save); resistance to acid.' },
  { key: 'blue', name: 'Blue', description: 'Lightning damage, 5×30 ft. line (Dex save); resistance to lightning.' },
  { key: 'brass', name: 'Brass', description: 'Fire damage, 5×30 ft. line (Dex save); resistance to fire.' },
  { key: 'bronze', name: 'Bronze', description: 'Lightning damage, 5×30 ft. line (Dex save); resistance to lightning.' },
  { key: 'copper', name: 'Copper', description: 'Acid damage, 5×30 ft. line (Dex save); resistance to acid.' },
  { key: 'gold', name: 'Gold', description: 'Fire damage, 15 ft. cone (Dex save); resistance to fire.' },
  { key: 'green', name: 'Green', description: 'Poison damage, 15 ft. cone (Con save); resistance to poison.' },
  { key: 'red', name: 'Red', description: 'Fire damage, 15 ft. cone (Dex save); resistance to fire.' },
  { key: 'silver', name: 'Silver', description: 'Cold damage, 15 ft. cone (Con save); resistance to cold.' },
  { key: 'white', name: 'White', description: 'Cold damage, 15 ft. cone (Con save); resistance to cold.' },
]

/** Half-Elf's real rule is +1 to two OTHER ability scores of the player's
 * choice, on top of the fixed +2 Cha — modeled as a proper choice now
 * rather than the flat approximation this used to ship with. */
const HALF_ELF_ABILITY_OPTIONS: FeatureChoiceOption[] = [
  { key: 'str', name: 'Strength' },
  { key: 'dex', name: 'Dexterity' },
  { key: 'con', name: 'Constitution' },
  { key: 'int', name: 'Intelligence' },
  { key: 'wis', name: 'Wisdom' },
]

/** Half-Elf's Skill Versatility — proficiency in two skills of your choice,
 * from the full skill list (not limited to a class's skill list). */
const HALF_ELF_SKILL_OPTIONS: FeatureChoiceOption[] = (Object.keys(SKILL_LABELS) as SkillId[]).map((id) => ({
  key: id,
  name: SKILL_LABELS[id],
}))

/** The 9 core PHB/SRD races, base version only — no subraces (e.g. "Elf"
 * rather than separately modeling High Elf/Wood Elf). */
export const SRD_RACES: RaceData[] = [
  { key: 'srd:human', source: 'srd', name: 'Human', size: 'Medium', speed: 30, abilityBonuses: { str: 1, dex: 1, con: 1, int: 1, wis: 1, cha: 1 }, traits: ['Extra language of your choice'], choices: [] },
  { key: 'srd:elf', source: 'srd', name: 'Elf', size: 'Medium', speed: 30, abilityBonuses: { dex: 2 }, traits: ['Darkvision 60 ft.', 'Advantage on saves vs. being charmed', "Doesn't need to sleep (trance 4 hrs)"], choices: [] },
  { key: 'srd:dwarf', source: 'srd', name: 'Dwarf', size: 'Medium', speed: 25, abilityBonuses: { con: 2 }, traits: ['Darkvision 60 ft.', 'Advantage on saves vs. poison', 'Resistance to poison damage'], choices: [] },
  { key: 'srd:halfling', source: 'srd', name: 'Halfling', size: 'Small', speed: 25, abilityBonuses: { dex: 2 }, traits: ['Lucky: reroll a 1 on attack/ability/save d20 rolls', 'Advantage on saves vs. being frightened'], choices: [] },
  {
    key: 'srd:dragonborn', source: 'srd', name: 'Dragonborn', size: 'Medium', speed: 30, abilityBonuses: { str: 2, cha: 1 },
    traits: ['Breath weapon and damage resistance depend on your Draconic Ancestry choice below'],
    choices: [{ id: 'draconic-ancestry', label: 'Draconic Ancestry', count: 1, options: DRACONIC_ANCESTRY_OPTIONS }],
  },
  { key: 'srd:gnome', source: 'srd', name: 'Gnome', size: 'Small', speed: 25, abilityBonuses: { int: 2 }, traits: ['Darkvision 60 ft.', 'Advantage on Int/Wis/Cha saves vs. magic'], choices: [] },
  {
    key: 'srd:half-elf', source: 'srd', name: 'Half-Elf', size: 'Medium', speed: 30, abilityBonuses: { cha: 2 },
    traits: ['Darkvision 60 ft.', 'Advantage on saves vs. being charmed'],
    choices: [
      { id: 'half-elf-ability-choice', label: 'Choose two other ability scores for +1 each', count: 2, grantsAbilityBonus: 1, options: HALF_ELF_ABILITY_OPTIONS },
      { id: 'half-elf-skill-choice', label: 'Skill Versatility — choose two skills', count: 2, grantsSkillProficiency: true, options: HALF_ELF_SKILL_OPTIONS },
    ],
  },
  { key: 'srd:half-orc', source: 'srd', name: 'Half-Orc', size: 'Medium', speed: 30, abilityBonuses: { str: 2, con: 1 }, traits: ['Darkvision 60 ft.', 'Relentless Endurance (drop to 1 HP instead of 0, 1/long rest)'], choices: [] },
  { key: 'srd:tiefling', source: 'srd', name: 'Tiefling', size: 'Medium', speed: 30, abilityBonuses: { cha: 2, int: 1 }, traits: ['Darkvision 60 ft.', 'Resistance to fire damage', 'Thaumaturgy cantrip'], choices: [] },
]

/** The 12 core PHB/SRD classes — single-class only (see CharacterRecord's
 * v1 limitation doc comment). `skillChoices` is the list a new character can
 * pick `skillChoiceCount` proficiencies from at creation; Bard's list is
 * genuinely "any skill" per SRD, so it lists all eighteen. */
const ALL_SKILLS_FOR_BARD: SkillId[] = [
  'acrobatics', 'animalHandling', 'arcana', 'athletics', 'deception', 'history', 'insight', 'intimidation',
  'investigation', 'medicine', 'nature', 'perception', 'performance', 'persuasion', 'religion', 'sleightOfHand',
  'stealth', 'survival',
]

/** Standard 5e Ability Score Improvement levels — Fighter and Rogue get
 * extras beyond the common [4,8,12,16,19]. */
const STANDARD_ASI_LEVELS = [4, 8, 12, 16, 19]

/** Fighting Style options — each PHB class that grants this feature offers a
 * different subset (mechanics-fact descriptions, written in my own words). */
const FIGHTING_STYLE_OPTIONS: Record<string, FeatureChoiceOption> = {
  archery: { key: 'archery', name: 'Archery', description: '+2 bonus to attack rolls with ranged weapons.' },
  defense: { key: 'defense', name: 'Defense', description: '+1 bonus to AC while wearing armor.' },
  dueling: { key: 'dueling', name: 'Dueling', description: '+2 damage with a one-handed melee weapon when wielding no other weapon.' },
  greatWeaponFighting: {
    key: 'great-weapon-fighting',
    name: 'Great Weapon Fighting',
    description: 'Reroll 1s and 2s on damage dice for two-handed/versatile melee weapons.',
  },
  protection: {
    key: 'protection',
    name: 'Protection',
    description: 'Use your reaction and a shield to impose disadvantage on an attack against a nearby ally.',
  },
  twoWeaponFighting: {
    key: 'two-weapon-fighting',
    name: 'Two-Weapon Fighting',
    description: "Add your ability modifier to your off-hand attack's damage.",
  },
}
const FIGHTER_FIGHTING_STYLES = Object.values(FIGHTING_STYLE_OPTIONS)
const PALADIN_FIGHTING_STYLES = [
  FIGHTING_STYLE_OPTIONS.defense,
  FIGHTING_STYLE_OPTIONS.dueling,
  FIGHTING_STYLE_OPTIONS.greatWeaponFighting,
  FIGHTING_STYLE_OPTIONS.protection,
]
const RANGER_FIGHTING_STYLES = [
  FIGHTING_STYLE_OPTIONS.archery,
  FIGHTING_STYLE_OPTIONS.defense,
  FIGHTING_STYLE_OPTIONS.dueling,
  FIGHTING_STYLE_OPTIONS.twoWeaponFighting,
]

export const SRD_CLASSES: ClassData[] = [
  {
    key: 'srd:barbarian', source: 'srd', name: 'Barbarian', hitDie: 12, savingThrows: ['str', 'con'], skillChoiceCount: 2,
    skillChoices: ['animalHandling', 'athletics', 'intimidation', 'nature', 'perception', 'survival'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 3,
    features: [
      { level: 1, name: 'Rage', entries: ['Bonus melee damage and resistance to bludgeoning/piercing/slashing damage while raging; limited uses per long rest.'] },
      { level: 1, name: 'Unarmored Defense', entries: ['AC = 10 + Dex mod + Con mod while not wearing armor.'] },
      { level: 2, name: 'Reckless Attack', entries: ['Advantage on melee Strength attacks this turn, but attacks against you have advantage until your next turn.'] },
      { level: 2, name: 'Danger Sense', entries: ['Advantage on Dex saves against effects you can see, like traps and spells.'] },
      { level: 3, name: 'Primal Path', entries: ['Choose a subclass.'] },
      { level: 5, name: 'Extra Attack', entries: ['Attack twice, instead of once, whenever you take the Attack action.'] },
      { level: 5, name: 'Fast Movement', entries: ['+10 ft. speed while not wearing heavy armor.'] },
      { level: 7, name: 'Feral Instinct', entries: ['Advantage on initiative; can act normally even if surprised, if you rage.'] },
      { level: 9, name: 'Brutal Critical', entries: ['Roll one extra weapon damage die on a critical hit.'] },
      { level: 11, name: 'Relentless Rage', entries: ['Chance to drop to 1 HP instead of 0 while raging.'] },
      { level: 15, name: 'Persistent Rage', entries: ['Your rage only ends early if you fall unconscious or choose to end it.'] },
      { level: 20, name: 'Primal Champion', entries: ['+4 Strength and Constitution, above the normal maximum.'] },
    ],
  },
  {
    key: 'srd:bard', source: 'srd', name: 'Bard', hitDie: 8, savingThrows: ['dex', 'cha'], skillChoiceCount: 3, skillChoices: ALL_SKILLS_FOR_BARD,
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 3,
    features: [
      { level: 1, name: 'Spellcasting', entries: ['Cast bard spells using Charisma.'] },
      { level: 1, name: 'Bardic Inspiration (d6)', entries: ['Give an ally a bonus die to add to one ability check, attack roll, or saving throw.'] },
      { level: 2, name: 'Jack of All Trades', entries: ['Add half your proficiency bonus to ability checks that don\'t already include it.'] },
      { level: 2, name: 'Song of Rest', entries: ['Extra healing for allies during a short rest.'] },
      { level: 3, name: 'Bard College', entries: ['Choose a subclass.'] },
      { level: 3, name: 'Expertise', entries: ['Double proficiency bonus on two chosen skill proficiencies.'] },
      { level: 5, name: 'Bardic Inspiration (d8)', entries: ['Bardic Inspiration die improves.'] },
      { level: 5, name: 'Font of Inspiration', entries: ['Regain all Bardic Inspiration uses on a short or long rest.'] },
      { level: 6, name: 'Countercharm', entries: ['Grant allies advantage on saves against being frightened or charmed.'] },
      { level: 10, name: 'Bardic Inspiration (d10)', entries: ['Bardic Inspiration die improves further.'] },
      { level: 10, name: 'Magical Secrets', entries: ['Learn spells from any class\'s spell list.'] },
      { level: 18, name: 'Bardic Inspiration (d12)', entries: ['Bardic Inspiration die improves further.'] },
      { level: 20, name: 'Superior Inspiration', entries: ['Regain one use of Bardic Inspiration when you roll initiative with none left.'] },
    ],
  },
  {
    key: 'srd:cleric', source: 'srd', name: 'Cleric', hitDie: 8, savingThrows: ['wis', 'cha'], skillChoiceCount: 2, skillChoices: ['history', 'insight', 'medicine', 'persuasion', 'religion'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 1,
    features: [
      { level: 1, name: 'Spellcasting', entries: ['Cast cleric spells using Wisdom.'] },
      { level: 1, name: 'Divine Domain', entries: ['Choose a subclass.'] },
      { level: 2, name: 'Channel Divinity', entries: ['Use a divine effect once per rest, refreshing on a short or long rest.'] },
      { level: 5, name: 'Destroy Undead', entries: ['Turned undead of low CR are destroyed instead of just fleeing.'] },
      { level: 6, name: 'Channel Divinity (2/rest)', entries: ['A second use of Channel Divinity between rests.'] },
      { level: 10, name: 'Divine Intervention', entries: ['Call on your deity for a powerful effect, chance-based.'] },
      { level: 18, name: 'Channel Divinity (3/rest)', entries: ['A third use of Channel Divinity between rests.'] },
      { level: 20, name: 'Divine Intervention Improvement', entries: ['Divine Intervention no longer requires a roll to succeed.'] },
    ],
  },
  {
    key: 'srd:druid', source: 'srd', name: 'Druid', hitDie: 8, savingThrows: ['int', 'wis'], skillChoiceCount: 2, skillChoices: ['arcana', 'animalHandling', 'insight', 'medicine', 'nature', 'perception', 'religion', 'survival'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 2,
    features: [
      { level: 1, name: 'Druidic', entries: ['Know the secret language of druids.'] },
      { level: 1, name: 'Spellcasting', entries: ['Cast druid spells using Wisdom.'] },
      { level: 2, name: 'Wild Shape', entries: ['Transform into a beast you\'ve seen, twice per short/long rest.'] },
      { level: 2, name: 'Druid Circle', entries: ['Choose a subclass.'] },
      { level: 18, name: 'Timeless Body', entries: ['Age much more slowly.'] },
      { level: 18, name: 'Beast Spells', entries: ['Cast spells while in Wild Shape form.'] },
      { level: 20, name: 'Archdruid', entries: ['Unlimited Wild Shape uses.'] },
    ],
  },
  {
    key: 'srd:fighter', source: 'srd', name: 'Fighter', hitDie: 10, savingThrows: ['str', 'con'], skillChoiceCount: 2, skillChoices: ['acrobatics', 'animalHandling', 'athletics', 'history', 'insight', 'intimidation', 'perception', 'survival'],
    asiLevels: [4, 6, 8, 12, 14, 16, 19], subclassLevel: 3,
    features: [
      {
        level: 1, name: 'Fighting Style', entries: ['Choose a combat specialization.'],
        choice: { id: 'fighting-style', label: 'Fighting Style', count: 1, options: FIGHTER_FIGHTING_STYLES },
      },
      { level: 1, name: 'Second Wind', entries: ['Bonus action to regain 1d10 + fighter level HP, once per short/long rest.'] },
      { level: 2, name: 'Action Surge', entries: ['Take one additional action on your turn, once per short/long rest.'] },
      { level: 3, name: 'Martial Archetype', entries: ['Choose a subclass.'] },
      { level: 5, name: 'Extra Attack', entries: ['Attack twice, instead of once, whenever you take the Attack action.'] },
      { level: 9, name: 'Indomitable', entries: ['Reroll a failed saving throw, once per long rest.'] },
      { level: 11, name: 'Extra Attack (2)', entries: ['Attack three times, instead of once, whenever you take the Attack action.'] },
      { level: 17, name: 'Action Surge (2 uses)', entries: ['A second use of Action Surge between rests.'] },
      { level: 20, name: 'Extra Attack (3)', entries: ['Attack four times, instead of once, whenever you take the Attack action.'] },
    ],
  },
  {
    key: 'srd:monk', source: 'srd', name: 'Monk', hitDie: 8, savingThrows: ['str', 'dex'], skillChoiceCount: 2, skillChoices: ['acrobatics', 'athletics', 'history', 'insight', 'religion', 'stealth'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 3,
    features: [
      { level: 1, name: 'Unarmored Defense', entries: ['AC = 10 + Dex mod + Wis mod while not wearing armor or a shield.'] },
      { level: 1, name: 'Martial Arts', entries: ['Use Dex for unarmed strikes/monk weapons; bonus-action unarmed strike; scaling martial arts die.'] },
      { level: 2, name: 'Ki', entries: ['A pool of Ki points (equal to monk level) fuels Flurry of Blows, Patient Defense, and Step of the Wind.'] },
      { level: 2, name: 'Unarmored Movement', entries: ['Speed increases while not wearing armor or a shield.'] },
      { level: 3, name: 'Monastic Tradition', entries: ['Choose a subclass.'] },
      { level: 3, name: 'Deflect Missiles', entries: ['Reduce ranged weapon damage, and can catch and throw it back.'] },
      { level: 4, name: 'Slow Fall', entries: ['Reduce fall damage using a reaction.'] },
      { level: 5, name: 'Extra Attack', entries: ['Attack twice, instead of once, whenever you take the Attack action.'] },
      { level: 5, name: 'Stunning Strike', entries: ['Spend a Ki point to attempt to stun a creature you hit.'] },
      { level: 6, name: 'Ki-Empowered Strikes', entries: ['Unarmed strikes count as magical for overcoming resistance/immunity.'] },
      { level: 7, name: 'Evasion', entries: ['Take no damage on a successful Dex save against an area effect, half on a failure.'] },
      { level: 7, name: 'Stillness of Mind', entries: ['End one effect causing you to be charmed or frightened, as an action.'] },
      { level: 10, name: 'Purity of Body', entries: ['Immune to disease and poison.'] },
      { level: 14, name: 'Diamond Soul', entries: ['Proficiency in all saving throws; spend a Ki point to reroll a failed save.'] },
      { level: 18, name: 'Empty Body', entries: ['Become invisible for a Ki cost; or spend Ki to astral project.'] },
      { level: 20, name: 'Perfect Self', entries: ['Regain 4 Ki points automatically if you roll initiative with none left.'] },
    ],
  },
  {
    key: 'srd:paladin', source: 'srd', name: 'Paladin', hitDie: 10, savingThrows: ['wis', 'cha'], skillChoiceCount: 2, skillChoices: ['athletics', 'insight', 'intimidation', 'medicine', 'persuasion', 'religion'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 3,
    features: [
      { level: 1, name: 'Divine Sense', entries: ['Detect celestials, fiends, and undead nearby, limited uses per long rest.'] },
      { level: 1, name: 'Lay on Hands', entries: ['A pool of HP (5 x paladin level) usable to heal, refreshing on a long rest.'] },
      {
        level: 2, name: 'Fighting Style', entries: ['Choose a combat specialization.'],
        choice: { id: 'fighting-style', label: 'Fighting Style', count: 1, options: PALADIN_FIGHTING_STYLES },
      },
      { level: 2, name: 'Spellcasting', entries: ['Cast paladin spells using Charisma.'] },
      { level: 2, name: 'Divine Smite', entries: ['Expend a spell slot on a melee hit for extra radiant damage.'] },
      { level: 3, name: 'Divine Health', entries: ['Immune to disease.'] },
      { level: 3, name: 'Sacred Oath', entries: ['Choose a subclass.'] },
      { level: 5, name: 'Extra Attack', entries: ['Attack twice, instead of once, whenever you take the Attack action.'] },
      { level: 6, name: 'Aura of Protection', entries: ['You and nearby allies add your Charisma modifier to saving throws.'] },
      { level: 10, name: 'Aura of Courage', entries: ['You and nearby allies can\'t be frightened while you are conscious.'] },
      { level: 14, name: 'Cleansing Touch', entries: ['End one spell affecting you or a willing creature you touch.'] },
    ],
  },
  {
    key: 'srd:ranger', source: 'srd', name: 'Ranger', hitDie: 10, savingThrows: ['str', 'dex'], skillChoiceCount: 3, skillChoices: ['animalHandling', 'athletics', 'insight', 'investigation', 'nature', 'perception', 'stealth', 'survival'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 3,
    features: [
      { level: 1, name: 'Favored Enemy', entries: ['Bonuses tracking/recalling info about a chosen creature type.'] },
      { level: 1, name: 'Natural Explorer', entries: ['Bonuses to travel and exploration within a chosen favored terrain.'] },
      {
        level: 2, name: 'Fighting Style', entries: ['Choose a combat specialization.'],
        choice: { id: 'fighting-style', label: 'Fighting Style', count: 1, options: RANGER_FIGHTING_STYLES },
      },
      { level: 2, name: 'Spellcasting', entries: ['Cast ranger spells using Wisdom.'] },
      { level: 3, name: 'Ranger Archetype', entries: ['Choose a subclass.'] },
      { level: 3, name: 'Primeval Awareness', entries: ['Expend a spell slot to sense certain creature types nearby.'] },
      { level: 5, name: 'Extra Attack', entries: ['Attack twice, instead of once, whenever you take the Attack action.'] },
      { level: 8, name: "Land's Stride", entries: ['Move through nonmagical difficult terrain at no cost.'] },
      { level: 10, name: 'Hide in Plain Sight', entries: ['Camouflage yourself for a large bonus to Stealth while stationary.'] },
      { level: 14, name: 'Vanish', entries: ['Hide as a bonus action; can\'t be tracked by nonmagical means.'] },
      { level: 18, name: 'Feral Senses', entries: ['Fight invisible creatures without disadvantage.'] },
      { level: 20, name: 'Foe Slayer', entries: ['Add your Wisdom modifier to an attack or damage roll against your favored enemy.'] },
    ],
  },
  {
    key: 'srd:rogue', source: 'srd', name: 'Rogue', hitDie: 8, savingThrows: ['dex', 'int'], skillChoiceCount: 4, skillChoices: ['acrobatics', 'athletics', 'deception', 'insight', 'intimidation', 'investigation', 'perception', 'performance', 'persuasion', 'sleightOfHand', 'stealth'],
    asiLevels: [4, 8, 10, 12, 16, 19], subclassLevel: 3,
    features: [
      { level: 1, name: 'Expertise', entries: ['Double proficiency bonus on two chosen skill (or thieves\' tools) proficiencies.'] },
      { level: 1, name: 'Sneak Attack', entries: ['Extra damage once per turn when you have advantage or an ally is adjacent to the target; dice scale with level.'] },
      { level: 1, name: "Thieves' Cant", entries: ['A secret rogue mode of communication.'] },
      { level: 2, name: 'Cunning Action', entries: ['Bonus action to Dash, Disengage, or Hide.'] },
      { level: 3, name: 'Roguish Archetype', entries: ['Choose a subclass.'] },
      { level: 5, name: 'Uncanny Dodge', entries: ['Halve damage from one attack you can see hitting you, as a reaction.'] },
      { level: 7, name: 'Evasion', entries: ['Take no damage on a successful Dex save against an area effect, half on a failure.'] },
      { level: 11, name: 'Reliable Talent', entries: ['Treat any ability check roll of 9 or lower as a 10, for proficient skills.'] },
      { level: 14, name: 'Blindsense', entries: ['Sense hidden or invisible creatures within 10 ft.'] },
      { level: 15, name: 'Slippery Mind', entries: ['Proficiency in Wisdom saving throws.'] },
      { level: 18, name: 'Elusive', entries: ['No attack roll has advantage against you while you aren\'t incapacitated.'] },
      { level: 20, name: 'Stroke of Luck', entries: ['Turn a missed attack into a hit, or a failed ability check into a 20.'] },
    ],
  },
  {
    key: 'srd:sorcerer', source: 'srd', name: 'Sorcerer', hitDie: 6, savingThrows: ['con', 'cha'], skillChoiceCount: 2, skillChoices: ['arcana', 'deception', 'insight', 'intimidation', 'persuasion', 'religion'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 1,
    features: [
      { level: 1, name: 'Spellcasting', entries: ['Cast sorcerer spells using Charisma.'] },
      { level: 1, name: 'Sorcerous Origin', entries: ['Choose a subclass.'] },
      { level: 2, name: 'Font of Magic', entries: ['A pool of Sorcery Points (equal to sorcerer level) usable to create spell slots or fuel Metamagic.'] },
      { level: 3, name: 'Metamagic', entries: ['Choose two ways to alter your spells using Sorcery Points (e.g. Quickened, Twinned).'] },
      { level: 20, name: 'Sorcerous Restoration', entries: ['Regain 4 Sorcery Points on a short rest.'] },
    ],
  },
  {
    key: 'srd:warlock', source: 'srd', name: 'Warlock', hitDie: 8, savingThrows: ['wis', 'cha'], skillChoiceCount: 2, skillChoices: ['arcana', 'deception', 'history', 'intimidation', 'investigation', 'nature', 'religion'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 1,
    features: [
      { level: 1, name: 'Otherworldly Patron', entries: ['Choose a subclass.'] },
      { level: 1, name: 'Pact Magic', entries: ['Cast warlock spells using Charisma, from a small number of slots that recharge on a short rest.'] },
      { level: 2, name: 'Eldritch Invocations', entries: ['Learn magical abilities that customize your warlock powers.'] },
      { level: 3, name: 'Pact Boon', entries: ['Choose a Pact Boon (Blade, Chain, or Tome).'] },
      { level: 11, name: 'Mystic Arcanum (6th level)', entries: ['Learn one 6th-level spell, castable once per long rest without a slot.'] },
      { level: 20, name: 'Eldritch Master', entries: ['Beg your patron to regain all Pact Magic slots, once per long rest.'] },
    ],
  },
  {
    key: 'srd:wizard', source: 'srd', name: 'Wizard', hitDie: 6, savingThrows: ['int', 'wis'], skillChoiceCount: 2, skillChoices: ['arcana', 'history', 'insight', 'investigation', 'medicine', 'religion'],
    asiLevels: STANDARD_ASI_LEVELS, subclassLevel: 2,
    features: [
      { level: 1, name: 'Spellcasting', entries: ['Cast wizard spells using Intelligence, prepared daily from your spellbook.'] },
      { level: 1, name: 'Arcane Recovery', entries: ['Recover some expended spell slots on a short rest, once per day.'] },
      { level: 2, name: 'Arcane Tradition', entries: ['Choose a subclass.'] },
      { level: 18, name: 'Spell Mastery', entries: ['Cast a chosen 1st- and 2nd-level spell at will without expending a slot.'] },
      { level: 20, name: 'Signature Spells', entries: ['Cast two chosen 3rd-level spells once each per short rest without expending a slot.'] },
    ],
  },
]

/** The SRD 5.1's one subclass per core class — same hand-authored,
 * mechanics-fact style as SRD_CLASSES/SRD_RACES above; a DM's imported
 * mirror is the path to the rest (see character-creation scope notes). */
export const SRD_SUBCLASSES: SubclassData[] = [
  {
    key: 'srd:barbarian-berserker', source: 'srd', name: 'Path of the Berserker', className: 'Barbarian',
    features: [
      { level: 3, name: 'Frenzy', entries: ['Make a bonus-action melee attack each turn you rage, at the cost of exhaustion once the rage ends.'] },
      { level: 6, name: 'Mindless Rage', entries: ['Can\'t be charmed or frightened while raging.'] },
      { level: 10, name: 'Intimidating Presence', entries: ['Frighten a creature as an action.'] },
      { level: 14, name: 'Retaliation', entries: ['Make a melee attack as a reaction against a creature that just damaged you.'] },
    ],
  },
  {
    key: 'srd:bard-lore', source: 'srd', name: 'College of Lore', className: 'Bard',
    features: [
      { level: 3, name: 'Bonus Proficiencies', entries: ['Proficiency in three additional skills.'] },
      { level: 3, name: 'Cutting Words', entries: ['Use Bardic Inspiration to subtract from an enemy\'s roll.'] },
      { level: 6, name: 'Additional Magical Secrets', entries: ['Learn two extra spells from any class\'s spell list.'] },
      { level: 14, name: 'Peerless Skill', entries: ['Add Bardic Inspiration to your own ability checks.'] },
    ],
  },
  {
    key: 'srd:cleric-life', source: 'srd', name: 'Life Domain', className: 'Cleric',
    features: [
      { level: 1, name: 'Bonus Proficiency & Disciple of Life', entries: ['Heavy armor proficiency; your healing spells restore extra hit points.'] },
      { level: 2, name: 'Channel Divinity: Preserve Life', entries: ['Restore a pool of hit points among nearby creatures.'] },
      { level: 6, name: 'Blessed Healer', entries: ['You also regain hit points when you heal others.'] },
      { level: 8, name: 'Divine Strike', entries: ['Extra radiant damage once per turn on a weapon hit.'] },
      { level: 17, name: 'Supreme Healing', entries: ['Healing spells restore the maximum possible amount instead of rolling.'] },
    ],
  },
  {
    key: 'srd:druid-land', source: 'srd', name: 'Circle of the Land', className: 'Druid',
    features: [
      { level: 2, name: 'Bonus Cantrip & Natural Recovery', entries: ['Learn an extra druid cantrip; recover some spell slots on a short rest.'] },
      { level: 3, name: 'Circle Spells', entries: ['Always-prepared bonus spells tied to your chosen land.'] },
      { level: 6, name: "Land's Stride", entries: ['Move through nonmagical difficult terrain at no cost.'] },
      { level: 10, name: "Nature's Ward", entries: ['Immune to poison and disease; can\'t be frightened by elementals or fey.'] },
      { level: 14, name: "Nature's Sanctuary", entries: ['Beasts and plants must save or be unable to attack you.'] },
    ],
  },
  {
    key: 'srd:fighter-champion', source: 'srd', name: 'Champion', className: 'Fighter',
    features: [
      { level: 3, name: 'Improved Critical', entries: ['Weapon attacks score a critical hit on a roll of 19 or 20.'] },
      { level: 7, name: 'Remarkable Athlete', entries: ['Add half proficiency bonus to Strength/Dexterity/Constitution checks that don\'t already use it.'] },
      { level: 10, name: 'Additional Fighting Style', entries: ['Learn a second Fighting Style.'] },
      { level: 15, name: 'Superior Critical', entries: ['Critical hit range expands to 18-20.'] },
      { level: 18, name: 'Survivor', entries: ['Regain hit points each turn if badly hurt.'] },
    ],
  },
  {
    key: 'srd:monk-open-hand', source: 'srd', name: 'Way of the Open Hand', className: 'Monk',
    features: [
      { level: 3, name: 'Open Hand Technique', entries: ['A hit from Flurry of Blows can knock prone, push, or prevent reactions.'] },
      { level: 6, name: 'Wholeness of Body', entries: ['Heal yourself using Ki, once per long rest.'] },
      { level: 11, name: 'Tranquility', entries: ['Effectively under a sanctuary spell between long rests.'] },
      { level: 17, name: 'Quivering Palm', entries: ['Set up lethal vibrations in a creature that can be triggered later.'] },
    ],
  },
  {
    key: 'srd:paladin-devotion', source: 'srd', name: 'Oath of Devotion', className: 'Paladin',
    features: [
      { level: 3, name: 'Channel Divinity: Sacred Weapon / Turn the Unholy', entries: ['Make your weapon magical and glowing, or turn fiends/undead.'] },
      { level: 7, name: 'Aura of Devotion', entries: ['You and nearby allies can\'t be charmed.'] },
      { level: 15, name: 'Purity of Spirit', entries: ['Effectively under a protection from evil and good spell at all times.'] },
      { level: 20, name: 'Holy Nimbus', entries: ['Emanate sunlight that damages fiends/undead and grants advantage vs. their spells.'] },
    ],
  },
  {
    key: 'srd:ranger-hunter', source: 'srd', name: 'Hunter', className: 'Ranger',
    features: [
      { level: 3, name: "Hunter's Prey", entries: ['Choose a combat option like Colossus Slayer or Horde Breaker.'] },
      { level: 7, name: 'Defensive Tactics', entries: ['Choose a defensive option like Escape the Horde or Multiattack Defense.'] },
      { level: 11, name: 'Multiattack', entries: ['Choose Volley or Whirlwind Attack to hit multiple nearby targets.'] },
      { level: 15, name: "Superior Hunter's Defense", entries: ['Choose a reaction option like Evasion or Stand Against the Tide.'] },
    ],
  },
  {
    key: 'srd:rogue-thief', source: 'srd', name: 'Thief', className: 'Rogue',
    features: [
      { level: 3, name: 'Fast Hands & Second-Story Work', entries: ['Cunning Action can also be used for object interaction/tools; better climbing and jumping.'] },
      { level: 9, name: 'Supreme Sneak', entries: ['Advantage on Stealth checks if you move at half speed.'] },
      { level: 13, name: 'Use Magic Device', entries: ['Ignore class/race/level requirements on using magic items.'] },
      { level: 17, name: "Thief's Reflexes", entries: ['Take two turns during the first round of combat.'] },
    ],
  },
  {
    key: 'srd:sorcerer-draconic', source: 'srd', name: 'Draconic Bloodline', className: 'Sorcerer',
    features: [
      { level: 1, name: 'Dragon Ancestor & Draconic Resilience', entries: ['Choose a dragon type; extra hit points and a natural armor bonus.'] },
      { level: 6, name: 'Elemental Affinity', entries: ['Add Charisma modifier to damage of spells matching your dragon type.'] },
      { level: 14, name: 'Dragon Wings', entries: ['Sprout wings and gain a flying speed.'] },
      { level: 18, name: 'Draconic Presence', entries: ['Awe or frighten creatures with your draconic presence.'] },
    ],
  },
  {
    key: 'srd:warlock-fiend', source: 'srd', name: 'The Fiend', className: 'Warlock',
    features: [
      { level: 1, name: "Dark One's Blessing", entries: ['Regain temporary hit points when you reduce a hostile creature to 0 HP.'] },
      { level: 6, name: "Dark One's Own Luck", entries: ['Add a bonus to one ability check or saving throw, once per rest.'] },
      { level: 10, name: 'Fiendish Resilience', entries: ['Choose a damage type to resist, changeable after a rest.'] },
      { level: 14, name: 'Hurl Through Hell', entries: ['Banish a creature you hit to another plane briefly, dealing psychic damage.'] },
    ],
  },
  {
    key: 'srd:wizard-evocation', source: 'srd', name: 'School of Evocation', className: 'Wizard',
    features: [
      { level: 2, name: 'Evocation Savant & Sculpt Spells', entries: ['Halved gold/time to copy evocation spells; protect allies from your own area spells.'] },
      { level: 6, name: 'Potent Cantrip', entries: ['Creatures that save against your cantrips still take half damage.'] },
      { level: 10, name: 'Empowered Evocation', entries: ['Add Intelligence modifier to one damage roll of an evocation spell.'] },
      { level: 14, name: 'Overchannel', entries: ['Deal maximum damage with a spell, at the cost of taking damage yourself on repeat use.'] },
    ],
  },
]

/** 6 core SRD 5.1 backgrounds — each grants exactly 2 fixed skill
 * proficiencies (a genuine 5e SRD rules fact, not a player choice) plus one
 * roleplay feature. Tool/language proficiencies and starting equipment
 * aren't modeled — this app's inventory is a plain unmechanical list, so
 * "equipment" wouldn't do anything mechanically anyway. */
export const SRD_BACKGROUNDS: BackgroundData[] = [
  {
    key: 'srd:acolyte', source: 'srd', name: 'Acolyte',
    skillProficiencies: ['insight', 'religion'],
    feature: { name: 'Shelter of the Faithful', entries: ['You and your companions can receive free healing and care at temples of your faith, and you have ties to a religious order.'] },
  },
  {
    key: 'srd:criminal', source: 'srd', name: 'Criminal',
    skillProficiencies: ['deception', 'stealth'],
    feature: { name: 'Criminal Contact', entries: ['You have a reliable contact in the criminal underworld who can relay messages and provide local information.'] },
  },
  {
    key: 'srd:folk-hero', source: 'srd', name: 'Folk Hero',
    skillProficiencies: ['animalHandling', 'survival'],
    feature: { name: 'Rustic Hospitality', entries: ['Common folk will shelter and provide minor aid to you, hiding you from obvious danger if needed.'] },
  },
  {
    key: 'srd:noble', source: 'srd', name: 'Noble',
    skillProficiencies: ['history', 'persuasion'],
    feature: { name: 'Position of Privilege', entries: ['You are welcomed in high society; commoners and nobles alike assume you have the right to be wherever you are.'] },
  },
  {
    key: 'srd:sage', source: 'srd', name: 'Sage',
    skillProficiencies: ['arcana', 'history'],
    feature: { name: 'Researcher', entries: ['When you don\'t know a piece of lore, you often know where to find it — a library, sage, or other knowledgeable source.'] },
  },
  {
    key: 'srd:soldier', source: 'srd', name: 'Soldier',
    skillProficiencies: ['athletics', 'intimidation'],
    feature: { name: 'Military Rank', entries: ['Soldiers loyal to your former organization recognize your authority and may offer aid or deference.'] },
  },
]
