import type { ItemData, MonsterData, SpellData } from './types'

/**
 * A small, hand-authored slice of the SRD 5.1 (Creative Commons CC-BY-4.0),
 * baked into the app as the always-available base fallback for the
 * compendium — works with zero configuration, before a DM ever points the
 * app at a private mirror (content/mirrorStorage.ts) or adds homebrew
 * (content/useHomebrewContent.ts). Deliberately small: this is a fallback/
 * demo set, not an attempt to reproduce the whole SRD — a private mirror is
 * the real path to full content per Phase 5's licensing note in ROADMAP.md.
 */

export const SRD_SPELLS: SpellData[] = [
  {
    key: 'srd:fire-bolt',
    source: 'srd',
    name: 'Fire Bolt',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes {@damage 1d10} fire damage. A flammable object hit by this spell ignites if it isn\'t being worn or carried.',
      'This spell\'s damage increases by {@dice 1d10} when you reach 5th level ({@dice 2d10}), 11th level ({@dice 3d10}), and 17th level ({@dice 4d10}).',
    ],
  },
  {
    key: 'srd:magic-missile',
    source: 'srd',
    name: 'Magic Missile',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals {@damage 1d4 + 1} force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.',
    ],
  },
  {
    key: 'srd:cure-wounds',
    source: 'srd',
    name: 'Cure Wounds',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger'],
    entries: [
      'A creature you touch regains a number of hit points equal to {@dice 1d8} + your spellcasting ability modifier.',
    ],
  },
  {
    key: 'srd:shield',
    source: 'srd',
    name: 'Shield',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 reaction, which you take when you are hit by an attack or targeted by magic missile',
    range: 'Self',
    components: 'V, S',
    duration: '1 round',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.',
    ],
  },
  {
    key: 'srd:fireball',
    source: 'srd',
    name: 'Fireball',
    level: 3,
    school: 'Evocation',
    castingTime: '1 action',
    range: '150 feet',
    components: 'V, S, M (a tiny ball of bat guano and sulfur)',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'A bright streak flashes from you to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a {@save dex}. A target takes {@damage 8d6} fire damage on a failed save, or half as much damage on a successful one.',
      'The fire spreads around corners. It ignites flammable objects in the area that aren\'t being worn or carried.',
    ],
  },
  {
    key: 'srd:acid-splash',
    source: 'srd',
    name: 'Acid Splash',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a {@save dex} or take {@damage 1d6} acid damage.',
      'This spell\'s damage increases by {@dice 1d6} when you reach 5th level ({@dice 2d6}), 11th level ({@dice 3d6}), and 17th level ({@dice 4d6}).',
    ],
  },
  {
    key: 'srd:guidance',
    source: 'srd',
    name: 'Guidance',
    level: 0,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S',
    duration: 'Concentration, up to 1 minute',
    classes: ['Cleric', 'Druid'],
    entries: [
      'You touch one willing creature. Once before the spell ends, the target can roll {@dice 1d4} and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check.',
    ],
  },
  {
    key: 'srd:light',
    source: 'srd',
    name: 'Light',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, M (a firefly or phosphorescent moss)',
    duration: '1 hour',
    classes: ['Bard', 'Cleric', 'Sorcerer', 'Wizard'],
    entries: [
      'You touch one object that is no larger than 10 feet in any dimension. Until the spell ends, the object sheds bright light in a 20-foot radius and dim light for an additional 20 feet.',
    ],
  },
  {
    key: 'srd:mage-hand',
    source: 'srd',
    name: 'Mage Hand',
    level: 0,
    school: 'Conjuration',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '1 minute',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it. You can use your action to control the hand, moving, manipulating, or carrying objects of up to 10 pounds.',
    ],
  },
  {
    key: 'srd:minor-illusion',
    source: 'srd',
    name: 'Minor Illusion',
    level: 0,
    school: 'Illusion',
    castingTime: '1 action',
    range: '30 feet',
    components: 'S, M (a bit of fleece)',
    duration: '1 minute',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'You create a sound or an image of an object within range that lasts for the duration. The illusion also ends if you dismiss it as an action or cast this spell again.',
    ],
  },
  {
    key: 'srd:prestidigitation',
    source: 'srd',
    name: 'Prestidigitation',
    level: 0,
    school: 'Transmutation',
    castingTime: '1 action',
    range: '10 feet',
    components: 'V, S',
    duration: 'Up to 1 hour',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'This spell is a minor magical trick that novice spellcasters use for practice: create a harmless sensory effect, light or snuff a small flame, clean or soil an object, chill/warm/flavor nonliving material, make a mark or symbol appear, or create a nonmagical trinket.',
    ],
  },
  {
    key: 'srd:sacred-flame',
    source: 'srd',
    name: 'Sacred Flame',
    level: 0,
    school: 'Evocation',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Cleric'],
    entries: [
      'Flame-like radiance descends on a creature that you can see within range. The target must succeed on a {@save dex} or take {@damage 1d8} radiant damage. The target gains no benefit from cover for this saving throw.',
      'The spell\'s damage increases by {@dice 1d8} when you reach 5th level ({@dice 2d8}), 11th level ({@dice 3d8}), and 17th level ({@dice 4d8}).',
    ],
  },
  {
    key: 'srd:vicious-mockery',
    source: 'srd',
    name: 'Vicious Mockery',
    level: 0,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    classes: ['Bard'],
    entries: [
      'You unleash a string of insults laced with subtle enchantments at a creature you can see within range. If the target can hear you, it must succeed on a {@save wis} or take {@damage 1d4} psychic damage and have disadvantage on the next attack roll it makes before the end of its next turn.',
      'This spell\'s damage increases by {@dice 1d4} when you reach 5th level ({@dice 2d4}), 11th level ({@dice 3d4}), and 17th level ({@dice 4d4}).',
    ],
  },
  {
    key: 'srd:burning-hands',
    source: 'srd',
    name: 'Burning Hands',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (15-foot cone)',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a {@save dex}. A target takes {@damage 3d6} fire damage on a failed save, or half as much damage on a successful one.',
      'The fire ignites any flammable objects in the area that aren\'t being worn or carried.',
    ],
  },
  {
    key: 'srd:charm-person',
    source: 'srd',
    name: 'Charm Person',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '30 feet',
    components: 'V, S',
    duration: '1 hour',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'You attempt to charm a humanoid you can see within range. It must make a {@save wis}, and does so with advantage if you or your companions are fighting it. If it fails the saving throw, it is charmed by you until the spell ends or until you or your companions do anything harmful to it. The charmed creature regards you as a friendly acquaintance.',
    ],
  },
  {
    key: 'srd:detect-magic',
    source: 'srd',
    name: 'Detect Magic',
    level: 1,
    school: 'Divination',
    castingTime: '1 action',
    range: 'Self',
    components: 'V, S',
    duration: 'Concentration, up to 10 minutes',
    classes: ['Bard', 'Cleric', 'Druid', 'Paladin', 'Ranger', 'Sorcerer', 'Wizard'],
    entries: [
      'For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object that bears magic, and learn its school of magic, if any.',
      'This spell can be cast as a ritual.',
    ],
  },
  {
    key: 'srd:guiding-bolt',
    source: 'srd',
    name: 'Guiding Bolt',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: '1 round',
    classes: ['Cleric'],
    entries: [
      'A flash of light streaks toward a creature of your choice within range. Make a ranged spell attack against the target. On a hit, the target takes {@damage 4d6} radiant damage, and the next attack roll made against this target before the end of your next turn has advantage.',
    ],
  },
  {
    key: 'srd:healing-word',
    source: 'srd',
    name: 'Healing Word',
    level: 1,
    school: 'Evocation',
    castingTime: '1 bonus action',
    range: '60 feet',
    components: 'V',
    duration: 'Instantaneous',
    classes: ['Bard', 'Cleric', 'Druid'],
    entries: [
      'A creature of your choice that you can see within range regains hit points equal to {@dice 1d4} + your spellcasting ability modifier. This spell has no effect on undead or constructs.',
    ],
  },
  {
    key: 'srd:mage-armor',
    source: 'srd',
    name: 'Mage Armor',
    level: 1,
    school: 'Abjuration',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M (a piece of cured leather)',
    duration: '8 hours',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You touch a willing creature who isn\'t wearing armor, and a protective magical force surrounds it until the spell ends. The target\'s base AC becomes 13 + its Dexterity modifier. The spell ends if the target dons armor or if you dismiss the spell as an action.',
    ],
  },
  {
    key: 'srd:sleep',
    source: 'srd',
    name: 'Sleep',
    level: 1,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '90 feet',
    components: 'V, S, M (a pinch of fine sand, rose petals, or a cricket)',
    duration: '1 minute',
    classes: ['Bard', 'Sorcerer', 'Wizard'],
    entries: [
      'This spell sends creatures into a magical slumber. Roll {@dice 5d8}; the total is how many hit points of creatures this spell can affect. Creatures within 20 feet of a point you choose within range are affected in ascending order of their current hit points (ignoring unconscious creatures).',
      'Starting with the creature that has the lowest current hit points, each creature affected by this spell falls unconscious until the spell ends, until it takes damage, or until someone uses an action to shake or slap the sleeper awake.',
    ],
  },
  {
    key: 'srd:thunderwave',
    source: 'srd',
    name: 'Thunderwave',
    level: 1,
    school: 'Evocation',
    castingTime: '1 action',
    range: 'Self (15-foot cube)',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Bard', 'Druid', 'Sorcerer', 'Wizard'],
    entries: [
      'A wave of thunderous force sweeps out from you. Each creature in a 15-foot cube originating from you must make a {@save con}. On a failed save, a creature takes {@damage 2d8} thunder damage and is pushed 10 feet away from you. On a successful save, the creature takes half as much damage and isn\'t pushed.',
      'Unsecured objects that are entirely within the area of effect are automatically pushed 10 feet away from you, and the spell emits a thunderous boom audible out to 300 feet.',
    ],
  },
  {
    key: 'srd:hold-person',
    source: 'srd',
    name: 'Hold Person',
    level: 2,
    school: 'Enchantment',
    castingTime: '1 action',
    range: '60 feet',
    components: 'V, S, M (a small, straight piece of iron)',
    duration: 'Concentration, up to 1 minute',
    classes: ['Bard', 'Cleric', 'Druid', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'You attempt to paralyze a humanoid you can see within range. It must succeed on a {@save wis} or be paralyzed for the duration. At the end of each of its turns, the target can make another Wisdom saving throw, ending the effect on itself on a success.',
    ],
  },
  {
    key: 'srd:invisibility',
    source: 'srd',
    name: 'Invisibility',
    level: 2,
    school: 'Illusion',
    castingTime: '1 action',
    range: 'Touch',
    components: 'V, S, M (an eyelash encased in gum arabic)',
    duration: 'Concentration, up to 1 hour',
    classes: ['Bard', 'Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target\'s person. The spell ends for a target that attacks or casts a spell.',
    ],
  },
  {
    key: 'srd:misty-step',
    source: 'srd',
    name: 'Misty Step',
    level: 2,
    school: 'Conjuration',
    castingTime: '1 bonus action',
    range: 'Self',
    components: 'V',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Warlock', 'Wizard'],
    entries: [
      'Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.',
    ],
  },
  {
    key: 'srd:scorching-ray',
    source: 'srd',
    name: 'Scorching Ray',
    level: 2,
    school: 'Evocation',
    castingTime: '1 action',
    range: '120 feet',
    components: 'V, S',
    duration: 'Instantaneous',
    classes: ['Sorcerer', 'Wizard'],
    entries: [
      'You create three rays of fire and hurl them at targets within range. You can hurl them at one target or several. Make a ranged spell attack for each ray. On a hit, the target takes {@damage 2d6} fire damage.',
    ],
  },
]

export const SRD_MONSTERS: MonsterData[] = [
  {
    key: 'srd:goblin',
    source: 'srd',
    name: 'Goblin',
    size: 'Small',
    type: 'humanoid (goblinoid)',
    alignment: 'Neutral Evil',
    ac: 15,
    acNote: 'leather armor, shield',
    hp: 7,
    hitDice: '2d6',
    speed: '30 ft.',
    abilities: { str: 8, dex: 14, con: 10, int: 10, wis: 8, cha: 8 },
    savingThrows: '',
    skills: 'Stealth +6',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'Common, Goblin',
    cr: '1/4',
    traits: [
      {
        name: 'Nimble Escape',
        entries: ['The goblin can take the Disengage or Hide action as a bonus action on each of its turns.'],
      },
    ],
    actions: [
      {
        name: 'Scimitar',
        entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 2} slashing damage.'],
      },
      {
        name: 'Shortbow',
        entries: [
          'Ranged Weapon Attack: {@hit 4} to hit, range 80/320 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:skeleton',
    source: 'srd',
    name: 'Skeleton',
    size: 'Medium',
    type: 'undead',
    alignment: 'Lawful Evil',
    ac: 13,
    acNote: 'armor scraps',
    hp: 13,
    hitDice: '2d8 + 4',
    speed: '30 ft.',
    abilities: { str: 10, dex: 14, con: 15, int: 6, wis: 8, cha: 5 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: 'poison',
    conditionImmunities: 'exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 9',
    languages: 'understands all languages it knew in life but can\'t speak',
    cr: '1/4',
    traits: [],
    actions: [
      {
        name: 'Shortsword',
        entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.'],
      },
      {
        name: 'Shortbow',
        entries: [
          'Ranged Weapon Attack: {@hit 4} to hit, range 80/320 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:wolf',
    source: 'srd',
    name: 'Wolf',
    size: 'Medium',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 13,
    acNote: 'natural armor',
    hp: 11,
    hitDice: '2d8 + 2',
    speed: '40 ft.',
    abilities: { str: 12, dex: 15, con: 12, int: 3, wis: 12, cha: 6 },
    savingThrows: '',
    skills: 'Perception +3, Stealth +4',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 13',
    languages: '',
    cr: '1/4',
    traits: [
      { name: 'Keen Hearing and Smell', entries: ['The wolf has advantage on Wisdom (Perception) checks that rely on hearing or smell.'] },
      {
        name: 'Pack Tactics',
        entries: ['The wolf has advantage on an attack roll against a creature if at least one of the wolf\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.'],
      },
    ],
    actions: [
      {
        name: 'Bite',
        entries: [
          'Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 2d4 + 2} piercing damage. If the target is a creature, it must succeed on a {@save str} or be knocked prone.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:orc',
    source: 'srd',
    name: 'Orc',
    size: 'Medium',
    type: 'humanoid (orc)',
    alignment: 'Chaotic Evil',
    ac: 13,
    acNote: 'hide armor',
    hp: 15,
    hitDice: '2d8 + 6',
    speed: '30 ft.',
    abilities: { str: 16, dex: 12, con: 16, int: 7, wis: 11, cha: 10 },
    savingThrows: '',
    skills: 'Intimidation +2',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'Common, Orc',
    cr: '1/2',
    traits: [
      { name: 'Aggressive', entries: ['As a bonus action, the orc can move up to its speed toward a hostile creature that it can see.'] },
    ],
    actions: [
      {
        name: 'Greataxe',
        entries: ['Melee Weapon Attack: {@hit 5} to hit, reach 5 ft., one target. Hit: {@damage 1d12 + 3} slashing damage.'],
      },
      {
        name: 'Javelin',
        entries: [
          'Melee or Ranged Weapon Attack: {@hit 5} to hit, reach 5 ft. or range 30/120 ft., one target. Hit: {@damage 1d6 + 3} piercing damage.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:giant-rat',
    source: 'srd',
    name: 'Giant Rat',
    size: 'Small',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 12,
    acNote: '',
    hp: 7,
    hitDice: '2d6',
    speed: '30 ft.',
    abilities: { str: 7, dex: 15, con: 11, int: 2, wis: 10, cha: 4 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: '',
    cr: '1/8',
    traits: [
      {
        name: 'Pack Tactics',
        entries: ['The rat has advantage on an attack roll against a creature if at least one of the rat\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.'],
      },
    ],
    actions: [
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d4 + 2} piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:rat',
    source: 'srd',
    name: 'Rat',
    size: 'Tiny',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 10,
    acNote: '',
    hp: 1,
    hitDice: '1d4 - 1',
    speed: '20 ft.',
    abilities: { str: 2, dex: 11, con: 9, int: 2, wis: 10, cha: 4 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 30 ft., passive Perception 10',
    languages: '',
    cr: '0',
    traits: [],
    actions: [
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 0} to hit, reach 5 ft., one target. Hit: 1 piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:kobold',
    source: 'srd',
    name: 'Kobold',
    size: 'Small',
    type: 'humanoid (kobold)',
    alignment: 'Lawful Evil',
    ac: 12,
    acNote: '',
    hp: 5,
    hitDice: '2d6 - 2',
    speed: '30 ft.',
    abilities: { str: 7, dex: 15, con: 9, int: 8, wis: 7, cha: 8 },
    savingThrows: '',
    skills: 'Stealth +4',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 8',
    languages: 'Common, Draconic',
    cr: '1/8',
    traits: [
      {
        name: 'Sunlight Sensitivity',
        entries: ['While in sunlight, the kobold has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.'],
      },
      {
        name: 'Pack Tactics',
        entries: ['The kobold has advantage on an attack roll against a creature if at least one of the kobold\'s allies is within 5 ft. of the creature and the ally isn\'t incapacitated.'],
      },
    ],
    actions: [
      { name: 'Dagger', entries: ['Melee or Ranged Weapon Attack: {@hit 4} to hit, reach 5 ft. or range 20/60 ft., one target. Hit: {@damage 1d4 + 2} piercing damage.'] },
      { name: 'Sling', entries: ['Ranged Weapon Attack: {@hit 4} to hit, range 30/120 ft., one target. Hit: {@damage 1d4 + 2} bludgeoning damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:bandit',
    source: 'srd',
    name: 'Bandit',
    size: 'Medium',
    type: 'humanoid (any race)',
    alignment: 'Any Non-Lawful',
    ac: 12,
    acNote: 'leather armor',
    hp: 11,
    hitDice: '2d8 + 2',
    speed: '30 ft.',
    abilities: { str: 11, dex: 12, con: 12, int: 10, wis: 10, cha: 10 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 10',
    languages: 'any one language (usually Common)',
    cr: '1/8',
    traits: [],
    actions: [
      { name: 'Scimitar', entries: ['Melee Weapon Attack: {@hit 3} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 1} slashing damage.'] },
      { name: 'Light Crossbow', entries: ['Ranged Weapon Attack: {@hit 3} to hit, range 80/320 ft., one target. Hit: {@damage 1d8 + 1} piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:zombie',
    source: 'srd',
    name: 'Zombie',
    size: 'Medium',
    type: 'undead',
    alignment: 'Neutral Evil',
    ac: 8,
    acNote: '',
    hp: 22,
    hitDice: '3d8 + 9',
    speed: '20 ft.',
    abilities: { str: 13, dex: 6, con: 16, int: 3, wis: 6, cha: 5 },
    savingThrows: 'Wis +0',
    skills: '',
    damageResistances: '',
    damageImmunities: 'poison',
    conditionImmunities: 'poisoned',
    senses: 'darkvision 60 ft., passive Perception 8',
    languages: 'understands the languages it knew in life but can\'t speak',
    cr: '1/4',
    traits: [
      {
        name: 'Undead Fortitude',
        entries: ['If damage reduces the zombie to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 hit point instead.'],
      },
    ],
    actions: [
      { name: 'Slam', entries: ['Melee Weapon Attack: {@hit 3} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 1} bludgeoning damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:black-bear',
    source: 'srd',
    name: 'Black Bear',
    size: 'Medium',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 11,
    acNote: 'natural armor',
    hp: 19,
    hitDice: '3d8 + 6',
    speed: '40 ft., climb 30 ft.',
    abilities: { str: 15, dex: 10, con: 14, int: 2, wis: 12, cha: 7 },
    savingThrows: '',
    skills: 'Perception +3',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 13',
    languages: '',
    cr: '1/2',
    traits: [{ name: 'Keen Smell', entries: ['The bear has advantage on Wisdom (Perception) checks that rely on smell.'] }],
    actions: [
      { name: 'Multiattack', entries: ['The bear makes two attacks: one with its bite and one with its claws.'] },
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 3} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 2} piercing damage.'] },
      { name: 'Claws', entries: ['Melee Weapon Attack: {@hit 3} to hit, reach 5 ft., one target. Hit: {@damage 2d4 + 2} slashing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:brown-bear',
    source: 'srd',
    name: 'Brown Bear',
    size: 'Large',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 11,
    acNote: 'natural armor',
    hp: 34,
    hitDice: '4d10 + 12',
    speed: '40 ft., climb 30 ft.',
    abilities: { str: 19, dex: 10, con: 16, int: 2, wis: 13, cha: 7 },
    savingThrows: '',
    skills: 'Perception +3',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'passive Perception 13',
    languages: '',
    cr: '1',
    traits: [{ name: 'Keen Smell', entries: ['The bear has advantage on Wisdom (Perception) checks that rely on smell.'] }],
    actions: [
      { name: 'Multiattack', entries: ['The bear makes two attacks: one with its bite and one with its claws.'] },
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 6} to hit, reach 5 ft., one target. Hit: {@damage 1d8 + 5} piercing damage.'] },
      { name: 'Claws', entries: ['Melee Weapon Attack: {@hit 6} to hit, reach 5 ft., one target. Hit: {@damage 2d6 + 5} slashing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:giant-spider',
    source: 'srd',
    name: 'Giant Spider',
    size: 'Large',
    type: 'beast',
    alignment: 'Unaligned',
    ac: 14,
    acNote: 'natural armor',
    hp: 26,
    hitDice: '4d10 + 4',
    speed: '30 ft., climb 30 ft.',
    abilities: { str: 14, dex: 16, con: 12, int: 2, wis: 11, cha: 4 },
    savingThrows: '',
    skills: 'Stealth +7',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'blindsight 10 ft., darkvision 60 ft., passive Perception 10',
    languages: '',
    cr: '1',
    traits: [
      { name: 'Spider Climb', entries: ['The spider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check.'] },
      { name: 'Web Sense', entries: ['While in contact with a web, the spider knows the exact location of any other creature in contact with the same web.'] },
      { name: 'Web Walker', entries: ['The spider ignores movement restrictions caused by webbing.'] },
    ],
    actions: [
      {
        name: 'Bite',
        entries: [
          'Melee Weapon Attack: {@hit 5} to hit, reach 5 ft., one creature. Hit: {@damage 1d8} piercing damage, and the target must make a {@save con} against a DC of 11, taking {@damage 2d8} poison damage on a failed save, or half as much on a success.',
        ],
      },
      {
        name: 'Web (Recharge 5-6)',
        entries: [
          'Ranged Weapon Attack: {@hit 5} to hit, range 30/60 ft., one creature. Hit: The target is restrained by webbing. As an action, the restrained creature can make a DC 11 Strength check, escaping on a success.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:ghoul',
    source: 'srd',
    name: 'Ghoul',
    size: 'Medium',
    type: 'undead',
    alignment: 'Chaotic Evil',
    ac: 12,
    acNote: '',
    hp: 22,
    hitDice: '5d8',
    speed: '30 ft.',
    abilities: { str: 13, dex: 15, con: 10, int: 7, wis: 10, cha: 6 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: 'poison',
    conditionImmunities: 'charmed, exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 10',
    languages: 'Common',
    cr: '1',
    traits: [],
    actions: [
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 2} to hit, reach 5 ft., one creature. Hit: {@damage 2d6 + 2} piercing damage.'] },
      {
        name: 'Claws',
        entries: [
          'Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one creature that isn\'t undead. Hit: {@damage 2d4 + 2} slashing damage. The target must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute.',
        ],
      },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:ogre',
    source: 'srd',
    name: 'Ogre',
    size: 'Large',
    type: 'giant',
    alignment: 'Chaotic Evil',
    ac: 11,
    acNote: 'hide armor',
    hp: 59,
    hitDice: '7d10 + 21',
    speed: '40 ft.',
    abilities: { str: 19, dex: 8, con: 16, int: 5, wis: 7, cha: 7 },
    savingThrows: '',
    skills: '',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 8',
    languages: 'Common, Giant',
    cr: '2',
    traits: [],
    actions: [
      { name: 'Greatclub', entries: ['Melee Weapon Attack: {@hit 6} to hit, reach 5 ft., one target. Hit: {@damage 2d8 + 4} bludgeoning damage.'] },
      { name: 'Javelin', entries: ['Melee or Ranged Weapon Attack: {@hit 6} to hit, reach 5 ft. or range 30/120 ft., one target. Hit: {@damage 2d6 + 4} piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:owlbear',
    source: 'srd',
    name: 'Owlbear',
    size: 'Large',
    type: 'monstrosity',
    alignment: 'Unaligned',
    ac: 13,
    acNote: 'natural armor',
    hp: 59,
    hitDice: '7d10 + 21',
    speed: '40 ft.',
    abilities: { str: 20, dex: 12, con: 17, int: 3, wis: 12, cha: 7 },
    savingThrows: '',
    skills: 'Perception +3',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 13',
    languages: '',
    cr: '3',
    traits: [{ name: 'Keen Sight and Smell', entries: ['The owlbear has advantage on Wisdom (Perception) checks that rely on sight or smell.'] }],
    actions: [
      { name: 'Multiattack', entries: ['The owlbear makes two attacks: one with its beak and one with its claws.'] },
      { name: 'Beak', entries: ['Melee Weapon Attack: {@hit 7} to hit, reach 5 ft., one creature. Hit: {@damage 1d10 + 5} piercing damage.'] },
      { name: 'Claws', entries: ['Melee Weapon Attack: {@hit 7} to hit, reach 5 ft., one target. Hit: {@damage 2d8 + 5} slashing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:wight',
    source: 'srd',
    name: 'Wight',
    size: 'Medium',
    type: 'undead',
    alignment: 'Neutral Evil',
    ac: 14,
    acNote: 'studded leather armor',
    hp: 45,
    hitDice: '6d8 + 18',
    speed: '30 ft.',
    abilities: { str: 15, dex: 14, con: 16, int: 10, wis: 13, cha: 15 },
    savingThrows: '',
    skills: 'Perception +3, Stealth +4',
    damageResistances: 'necrotic; bludgeoning, piercing, and slashing from nonmagical attacks',
    damageImmunities: 'poison',
    conditionImmunities: 'exhaustion, poisoned',
    senses: 'darkvision 60 ft., passive Perception 13',
    languages: 'the languages it knew in life',
    cr: '3',
    traits: [
      {
        name: 'Sunlight Sensitivity',
        entries: ['While in sunlight, the wight has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight.'],
      },
    ],
    actions: [
      { name: 'Multiattack', entries: ['The wight makes two longsword attacks or two longbow attacks. It can use its Life Drain in place of one longsword attack.'] },
      {
        name: 'Life Drain',
        entries: [
          'Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one creature. Hit: {@damage 1d6 + 2} necrotic damage. The target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken, and the wight regains hit points equal to that amount. The reduction lasts until the target finishes a long rest. The target dies if this effect reduces its hit point maximum to 0. A humanoid slain by this attack rises 24 hours later as a zombie under the wight\'s control, unless the humanoid is restored to life or its body is destroyed.',
        ],
      },
      { name: 'Longsword', entries: ['Melee Weapon Attack: {@hit 4} to hit, reach 5 ft., one target. Hit: {@damage 1d8 + 2} slashing damage, or {@damage 1d10 + 2} if used with two hands.'] },
      { name: 'Longbow', entries: ['Ranged Weapon Attack: {@hit 4} to hit, range 150/600 ft., one target. Hit: {@damage 1d8 + 2} piercing damage.'] },
    ],
    legendaryActions: [],
  },
  {
    key: 'srd:troll',
    source: 'srd',
    name: 'Troll',
    size: 'Large',
    type: 'giant',
    alignment: 'Chaotic Evil',
    ac: 15,
    acNote: 'natural armor',
    hp: 84,
    hitDice: '8d10 + 40',
    speed: '30 ft.',
    abilities: { str: 18, dex: 13, con: 20, int: 7, wis: 9, cha: 7 },
    savingThrows: '',
    skills: 'Perception +2',
    damageResistances: '',
    damageImmunities: '',
    conditionImmunities: '',
    senses: 'darkvision 60 ft., passive Perception 12',
    languages: 'Giant',
    cr: '5',
    traits: [
      { name: 'Keen Smell', entries: ['The troll has advantage on Wisdom (Perception) checks that rely on smell.'] },
      {
        name: 'Regeneration',
        entries: [
          'The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, this trait doesn\'t function at the start of the troll\'s next turn. The troll dies only if it starts its turn with 0 hit points and doesn\'t regenerate.',
        ],
      },
    ],
    actions: [
      { name: 'Multiattack', entries: ['The troll makes three attacks: one with its bite and two with its claws.'] },
      { name: 'Bite', entries: ['Melee Weapon Attack: {@hit 7} to hit, reach 5 ft., one target. Hit: {@damage 1d6 + 4} piercing damage.'] },
      { name: 'Claw', entries: ['Melee Weapon Attack: {@hit 7} to hit, reach 5 ft., one target. Hit: {@damage 2d6 + 4} slashing damage.'] },
    ],
    legendaryActions: [],
  },
]

export const SRD_ITEMS: ItemData[] = [
  {
    key: 'srd:longsword',
    source: 'srd',
    name: 'Longsword',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '3 lb.',
    value: '15 gp',
    entries: ['Versatile (1d10). {@damage 1d8} slashing damage, or {@damage 1d10} if used with two hands.'],
  },
  {
    key: 'srd:dagger',
    source: 'srd',
    name: 'Dagger',
    type: 'Weapon (simple melee)',
    rarity: 'none',
    weight: '1 lb.',
    value: '2 gp',
    entries: ['Finesse, light, thrown (range 20/60). {@damage 1d4} piercing damage.'],
  },
  {
    key: 'srd:leather-armor',
    source: 'srd',
    name: 'Leather Armor',
    type: 'Armor (light)',
    rarity: 'none',
    weight: '10 lb.',
    value: '10 gp',
    entries: ['AC 11 + Dex modifier.'],
  },
  {
    key: 'srd:shield',
    source: 'srd',
    name: 'Shield',
    type: 'Armor (shield)',
    rarity: 'none',
    weight: '6 lb.',
    value: '10 gp',
    entries: ['+2 AC while wielded.'],
  },
  {
    key: 'srd:potion-of-healing',
    source: 'srd',
    name: 'Potion of Healing',
    type: 'Potion',
    rarity: 'common',
    weight: '0.5 lb.',
    value: '50 gp',
    entries: ['You regain {@dice 2d4 + 2} hit points when you drink this potion.'],
  },
  {
    key: 'srd:shortsword',
    source: 'srd',
    name: 'Shortsword',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '2 lb.',
    value: '10 gp',
    entries: ['Finesse, light. {@damage 1d6} piercing damage.'],
  },
  {
    key: 'srd:greatsword',
    source: 'srd',
    name: 'Greatsword',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '6 lb.',
    value: '50 gp',
    entries: ['Heavy, two-handed. {@damage 2d6} slashing damage.'],
  },
  {
    key: 'srd:rapier',
    source: 'srd',
    name: 'Rapier',
    type: 'Weapon (martial melee)',
    rarity: 'none',
    weight: '2 lb.',
    value: '25 gp',
    entries: ['Finesse. {@damage 1d8} piercing damage.'],
  },
  {
    key: 'srd:shortbow',
    source: 'srd',
    name: 'Shortbow',
    type: 'Weapon (simple ranged)',
    rarity: 'none',
    weight: '2 lb.',
    value: '25 gp',
    entries: ['Ammunition (range 80/320), two-handed. {@damage 1d6} piercing damage.'],
  },
  {
    key: 'srd:handaxe',
    source: 'srd',
    name: 'Handaxe',
    type: 'Weapon (simple melee)',
    rarity: 'none',
    weight: '2 lb.',
    value: '5 gp',
    entries: ['Light, thrown (range 20/60). {@damage 1d6} slashing damage.'],
  },
  {
    key: 'srd:studded-leather-armor',
    source: 'srd',
    name: 'Studded Leather Armor',
    type: 'Armor (light)',
    rarity: 'none',
    weight: '13 lb.',
    value: '45 gp',
    entries: ['AC 12 + Dex modifier.'],
  },
  {
    key: 'srd:chain-mail',
    source: 'srd',
    name: 'Chain Mail',
    type: 'Armor (heavy)',
    rarity: 'none',
    weight: '55 lb.',
    value: '75 gp',
    entries: ['AC 16. Str 13 required; disadvantage on Stealth checks.'],
  },
  {
    key: 'srd:rope-hempen',
    source: 'srd',
    name: 'Rope, Hempen (50 feet)',
    type: 'Adventuring Gear',
    rarity: 'none',
    weight: '10 lb.',
    value: '1 gp',
    entries: ['Rope has 2 hit points and can be burst with a DC 17 Strength check.'],
  },
  {
    key: 'srd:backpack',
    source: 'srd',
    name: 'Backpack',
    type: 'Adventuring Gear',
    rarity: 'none',
    weight: '5 lb.',
    value: '2 gp',
    entries: ['A backpack can hold one cubic foot or 30 pounds of gear. You can also strap items, such as a bedroll or a coil of rope, to the outside of a backpack.'],
  },
  {
    key: 'srd:torch',
    source: 'srd',
    name: 'Torch',
    type: 'Adventuring Gear',
    rarity: 'none',
    weight: '1 lb.',
    value: '1 cp',
    entries: ['A torch burns for 1 hour, providing bright light in a 20-foot radius and dim light for an additional 20 feet. If you make a melee attack with a burning torch and hit, it deals 1 fire damage.'],
  },
  {
    key: 'srd:thieves-tools',
    source: 'srd',
    name: "Thieves' Tools",
    type: 'Tool',
    rarity: 'none',
    weight: '1 lb.',
    value: '25 gp',
    entries: ['This set includes a small file, lock picks, small mirror on a metal handle, narrow-bladed scissors, and pliers. Proficiency with these tools lets you add your proficiency bonus to checks made to disarm traps or open locks.'],
  },
  {
    key: 'srd:bag-of-holding',
    source: 'srd',
    name: 'Bag of Holding',
    type: 'Wondrous item',
    rarity: 'uncommon',
    weight: '15 lb.',
    value: '',
    entries: [
      'This bag has an interior space considerably larger than its outside dimensions, roughly 2 feet in diameter at the mouth and 4 feet deep. The bag can hold up to 500 pounds, not exceeding a volume of 64 cubic feet. The bag weighs 15 pounds, regardless of its contents.',
      'Placing an object that is small enough to fit inside the bag causes the bag to absorb it, making the object weightless and taking up a negligible amount of space in the bag.',
      'If the bag is overloaded, or if a sharp object pierces it, the bag ruptures and is destroyed, and its contents are scattered in the Astral Plane.',
    ],
  },
]
